Reklama/Models/Shared/BaseModel.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using Domain.Entity.Shared;
using Domain.Repository.Shared;
using System.Data;
using Reklama.Models;
using System.Data.Entity;

namespace Reklama.Models.Shared
{
    public class BaseModel<T> : IRepository<T>
        where T : BaseEntity
    {
        private ReklamaContext _context = null;

        public DbContext Context
        {
            get
            {
                if (_context != null)
                {
                    return _context;
                }
                else
                {
                    throw new DataException("The DbContext cannot be null");
                }
            }
            set
            {
                if (value != null)
                {
                    _context = (ReklamaContext)value;
                }
            }
        }

        public virtual int Save(T entity)
        {
            T entitydb;

            if (entity.Id != 0)
            {
                entitydb = entity;
                Context.Set<T>().AddOrUpdate(entity);
            }
            else
            {
                entitydb = Context.Set<T>().Add(entity);
            }

            try
            {
                Context.SaveChanges();
                
            }
            catch (DbEntityValidationException ex)
            {
                var error = ex.EntityValidationErrors.First().ValidationErrors.First();
                var erors = ex.EntityValidationErrors.ToList();
                
                
            } 
            
            return entitydb.Id;
        }

        public virtual void Delete(T entity)
        {
            Context.Set<T>().Remove(entity);
            Context.SaveChanges();
        }

        public virtual T Read(int id)
        {
            return (from r in Context.Set<T>() where r.Id.Equals(id) select r).FirstOrDefault();
        }

        public virtual IQueryable<T> Read()
        {
            return from r in Context.Set<T>() select r;
        }


        public virtual IQueryable<T> FilterCollection(Func<T, bool> predicate)
        {
            return Context.Set<T>().Where(predicate).AsQueryable();
        }

        public virtual T FilterOne(Func<T, bool> predicate)
        {
            return Context.Set<T>().First(predicate);
        }

        public virtual IQueryable<T> Filter(IQueryable<T> collection, Func<T, bool> predicate)
        {
            return collection.Where(predicate).AsQueryable();
        }
    }
}

Reklama/Controllers/AdminController.cs
using System.Drawing.Drawing2D;
using Domain.Entity.Admin;
using Domain.Entity.Catalogs;
using Domain.Entity.Other;
using Domain.Entity.Shared;
using Domain.Repository.Admin;
using Domain.Repository.Announcements;
using Domain.Repository.Articles;
using Domain.Repository.Catalogs;
using Domain.Repository.Other;
using Domain.Repository.Shared;
using Domain.ViewModels.Banners;
using Reklama.Data.Entities;
using Reklama.Data.Servises;
using Reklama.Models;
using Reklama.Models.ViewModels.Admin;
using Reklama.Models.ViewModels.Shared;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebMatrix.WebData;
using PagedList;
using Product = Domain.Entity.Catalogs.Product;
using Unit = Domain.Entity.Catalogs.Unit;

namespace Reklama.Controllers
{
    [Authorize(Roles = "Administrator, Moderator")]
    public class AdminController : Controller
    {
        private ReklamaContext rc = new ReklamaContext();

        private readonly IConfigRepository _configRepository;
        private readonly IMenuRepository _menuRepository;
        private readonly IMenuPageRefRepository _menuPageRefRepository;
        private readonly IPageRepository _pageRepository;
        private readonly ICurrencyRepository _currencyRepository;
        private readonly IPremiumRepository _premiumRepository;
        private readonly IAnnouncementConfigRepository _announcementConfigRepository;
        private readonly IArticleConfigRepository _articleConfigRepository;
        private readonly IMainPageArticleConfigRepository _mainPageArticleConfigRepository;
        private readonly IProfileRepository _profileRepository;
        private readonly IAnnouncementRepository _announcementRepository;
        private readonly IArticleRepository _articleRepository;
        private readonly IAnnouncementsPremiumsRefRepository _announcementsPremiumsRefRepository;
        private readonly ICatalogParamSubsectionRepository _catalogParamSubsectionRepository;
        private readonly IUnitRepository _unitRepository;
        private readonly IProductRepository _productRepository;
        private readonly IProductParamRepository _productParamRepository;
        private readonly IProductParamValueRepository _productParamValueRepository;
        private readonly IProductSectionParamRefRepository _productSectionParamRefRepository;
        private readonly IProductSubsectionParamRefRepository _productSubsectionParamRefRepository;
        private readonly ICatalogCategoryRepository _catalogCategoryRepository;
        private readonly ICatalogSecondCategoryRepository _catalogSecondCategoryRepository;
        private readonly IShopRepository _shopRepository;
        private readonly IShopCategoryRefRepository _shopCategoryRefRepository;
        private readonly IProductImageRepository _productImageRepository;
        private readonly ICatalogConfigRepository _catalogConfigRepository;
        private readonly ICatalogThirdCategoryRepository _catalogThirdCategoryRepository;
        private readonly IPopularSectionInCatalogRepository _popularSectionInCatalogRepository;
        private readonly INewSectionInCatalogRepository _newSectionInCatalogRepository;
        private readonly IPopularProductRepository _popularProductRepository;
        private readonly IPopularAnnouncementRepository _popularAnnouncementRepository;
        private readonly ISectionRepository _sectionRepository;
        private readonly ISubsectionRepository _subsectionRepository;


        public AdminController(IConfigRepository configRepository, IPageRepository pageRepository,
            IMenuRepository menuRepository, IMenuPageRefRepository menuPageRefRepository,
            ICurrencyRepository currencyRepository, IPremiumRepository premiumRepository,
            IAnnouncementConfigRepository announcementConfigRepository, IArticleConfigRepository articleConfigRepository,
            IProfileRepository profileRepository, IAnnouncementRepository announcementRepository,
            IArticleRepository articleRepository, IAnnouncementsPremiumsRefRepository announcementsPremiumsRefRepository,
            IUnitRepository unitRepository, IProductParamRepository productParamRepository,
            IProductSectionParamRefRepository productSectionParamRefRepository, IProductSubsectionParamRefRepository productSubsectionParamRefRepository,
            IProductRepository productRepository, ICatalogCategoryRepository catalogCategoryRepository,
            IShopRepository shopRepository, ICatalogSecondCategoryRepository catalogSecondCategoryRepository, IShopCategoryRefRepository shopCategoryRefRepository,
            IProductImageRepository productImageRepository, IProductParamValueRepository productParamValueRepository,
            ICatalogParamSubsectionRepository catalogParamSubsectionRepository, ICatalogConfigRepository catalogConfigRepository,
            ICatalogThirdCategoryRepository catalogThirdCategoryRepository, IPopularSectionInCatalogRepository popularSectionInCatalogRepository,
            INewSectionInCatalogRepository newSectionInCatalogRepository, IPopularProductRepository popularProductRepository,
            IMainPageArticleConfigRepository mainPageArticleConfigRepository, IPopularAnnouncementRepository popularAnnouncementRepository,
            ISectionRepository sectionRepository, ISubsectionRepository subsectionRepository)
        {
            _configRepository = configRepository;
            _configRepository.Context = rc;

            _pageRepository = pageRepository;
            _pageRepository.Context = rc;

            _menuRepository = menuRepository;
            _menuRepository.Context = rc;

            _menuPageRefRepository = menuPageRefRepository;
            _menuPageRefRepository.Context = rc;

            _currencyRepository = currencyRepository;
            _currencyRepository.Context = rc;

            _premiumRepository = premiumRepository;
            _premiumRepository.Context = rc;

            _announcementConfigRepository = announcementConfigRepository;
            _announcementConfigRepository.Context = rc;

            _articleConfigRepository = articleConfigRepository;
            _articleConfigRepository.Context = rc;

            _profileRepository = profileRepository;
            _profileRepository.Context = rc;

            _announcementRepository = announcementRepository;
            _announcementRepository.Context = rc;

            _articleRepository = articleRepository;
            _articleRepository.Context = rc;

            _announcementsPremiumsRefRepository = announcementsPremiumsRefRepository;
            _announcementsPremiumsRefRepository.Context = rc;

            _catalogParamSubsectionRepository = catalogParamSubsectionRepository;
            _catalogParamSubsectionRepository.Context = rc;

            _unitRepository = unitRepository;
            _unitRepository.Context = rc;

            _productParamRepository = productParamRepository;
            _productParamRepository.Context = rc;

            _productSectionParamRefRepository = productSectionParamRefRepository;
            _productSectionParamRefRepository.Context = rc;

            _productSubsectionParamRefRepository = productSubsectionParamRefRepository;
            _productSubsectionParamRefRepository.Context = rc;

            _productRepository = productRepository;
            _productRepository.Context = rc;

            _catalogCategoryRepository = catalogCategoryRepository;
            _catalogCategoryRepository.Context = rc;

            _shopRepository = shopRepository;
            _shopRepository.Context = rc;

            _catalogSecondCategoryRepository = catalogSecondCategoryRepository;
            _catalogSecondCategoryRepository.Context = rc;

            _shopCategoryRefRepository = shopCategoryRefRepository;
            _shopCategoryRefRepository.Context = rc;

            _productImageRepository = productImageRepository;
            _productImageRepository.Context = rc;

            _productParamValueRepository = productParamValueRepository;
            _productParamValueRepository.Context = rc;

            _catalogConfigRepository = catalogConfigRepository;
            _catalogConfigRepository.Context = rc;

            _catalogThirdCategoryRepository = catalogThirdCategoryRepository;
            _catalogThirdCategoryRepository.Context = rc;

            _popularSectionInCatalogRepository = popularSectionInCatalogRepository;
            _popularSectionInCatalogRepository.Context = rc;

            _newSectionInCatalogRepository = newSectionInCatalogRepository;
            _newSectionInCatalogRepository.Context = rc;

            _popularProductRepository = popularProductRepository;
            _popularProductRepository.Context = rc;

            _mainPageArticleConfigRepository = mainPageArticleConfigRepository;
            _mainPageArticleConfigRepository.Context = rc;

            _popularAnnouncementRepository = popularAnnouncementRepository;
            _popularAnnouncementRepository.Context = rc;

            _sectionRepository = sectionRepository;
            _sectionRepository.Context = rc;

            _subsectionRepository = subsectionRepository;
            _subsectionRepository.Context = rc;
        }

        /**
         * Общие настройки
         */
        #region General
        [Authorize(Roles = "Administrator")]
        public ActionResult General()
        {
            List<Config> configs = _configRepository.Read().ToList();
            return View(configs);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult General(List<Config> configs)
        {
            try
            {
                foreach (var config in configs)
                {
                    _configRepository.Save(config);
                }
                TempData["Message"] = "Все изменения сохранены";
            }

Reklama/Controllers/LinksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Entity.Admin;
using Domain.Repository.Admin;
using Domain.Repository.Other;
using Reklama.Models;


namespace Reklama.Controllers
{
    public class LinksController : Controller
    {
        private ReklamaContext rc = new ReklamaContext();

        private readonly IConfigRepository _configRepository;
        private readonly IPageRepository _pageRepository;

        public LinksController(IConfigRepository configRepository, IPageRepository pageRepository)
        {
            _configRepository = configRepository;
            _configRepository.Context = rc;

            _pageRepository = pageRepository;
            _pageRepository.Context = rc;
        }

        public ActionResult ViewSocialLinks()
        {
            ViewBag.Facebook = _configRepository.ReadByName("LinkFacebook").Value;
            ViewBag.Vk = _configRepository.ReadByName("LinkVk").Value;
            ViewBag.Twitter = _configRepository.ReadByName("LinkTwitter").Value;
            ViewBag.GooglePlus = _configRepository.ReadByName("LinkGooglePlus").Value;
            ViewBag.Odnoklassniki = _configRepository.ReadByName("LinkOdnoklassniki").Value;
            ViewBag.Mail = _configRepository.ReadByName("LinkMail").Value;
            return View();
        }


        /**
         * Отображает ссылку на одну из основных страниц, указанных в конфиге
         * (например, Пользовательское соглашение)
         */
        public ActionResult LinkToOneOfMainConfigPage(string mainPageName, string target = "_self", string cssClass = null)
        {
            try
            {
                var config = _configRepository.ReadByName(mainPageName);
                ViewBag.Page = _pageRepository.Read(Convert.ToInt32(config.Value));
                ViewBag.CssClass = cssClass;
                ViewBag.Target = target;
                return View(config);
            }
            catch
            {
                return null;
            }
        }


        protected override void Dispose(bool disposing)
        {
            rc.Dispose();
            base.Dispose(disposing);
        }
    }
}

Reklama/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Entity.Other;
using Domain.Repository.Other;
using Reklama.Models;

namespace Reklama.Controllers
{
    public class MenuController : Controller
    {
        private ReklamaContext rc = new ReklamaContext();

        private IMenuRepository _menuRepository;
        private IMenuPageRefRepository _menuPageRefRepository;
        private IPageRepository _pageRepository;

        public MenuController(IMenuRepository menuRepository, 
            IMenuPageRefRepository menuPageRefRepository,
            IPageRepository pageRepository)
        {
            _menuRepository = menuRepository;
            _menuRepository.Context = rc;

            _menuPageRefRepository = menuPageRefRepository;
            _menuPageRefRepository.Context = rc;

            _pageRepository = pageRepository;
            _pageRepository.Context = rc;
        }

        public ActionResult UnderLogoMenu()
        {
            var menu = _menuRepository.ReadByName("UnderLogoMenu");
            var menusPages = menu.MenuPageRefs.OrderBy(r => r.Priority);
            return View(menusPages);
        }


        public ActionResult AllsDropDownMenu()
        {
            var menu = _menuRepository.ReadByName("AllsDropDownMenu");
            var menusPages = menu.MenuPageRefs.OrderBy(r => r.Priority);
            return View(menusPages);
        }


        public ActionResult FooterMenu()
        {
            try
            {
                var menu = _menuRepository.ReadByName("FooterMenu");
                var menusPages = menu.MenuPageRefs.OrderBy(r => r.Priority);
                return View(menusPages);
            }
            catch
            {
                return null;
            }
        }


        public ActionResult FooterBottomMenu()
        {
            try
            {
                var menu = _menuRepository.ReadByName("FooterBottomMenu");
                var menusPages = menu.MenuPageRefs.OrderBy(r => r.Priority);
                return View(menusPages);
            }
            catch(Exception) {
                return null;
            }
        }


        public ActionResult ListMenus()
        {
            var menus = _menuRepository.Read();
            return View(menus);
        }


        private void PopulateMenuDropDownList(object selectedMenu = null)
        {
            var menus = _menuRepository.Read();
            ViewBag.Menus = new SelectList(menus, "Id", "Name", selectedMenu);
        }

        private void PopulatePageDropDownList(object selectedPage = null)
        {
            var pages = _pageRepository.Read();
            ViewBag.Pages = new SelectList(pages, "Id", "Name", selectedPage);
        }



        protected override void Dispose(bool disposing)
        {
            rc.Dispose();
            base.Dispose(disposing);
        }
    }
}

Reklama/Views/Shared/_Layout.cshtml
@using System.Web.Configuration
@using Infrastructure.Helpers
@using Reklama.Models.ViewModels.Shared
@using Reklama;
@using Domain.Enums;

@{
    
    var selectedSiteCategory = (ViewBag.SelectedSiteCategory != null) ? (CategorySearch)ViewBag.SelectedSiteCategory : CategorySearch.Product;
}
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>@ViewBag.Title</title>
    <meta content="" name="keywords">
    <meta content="" name="description">
    <link rel="shortcut icon" href="@Url.Content("~/Images/System/favicon.ico")" type="image/x-icon" />
    <link rel="icon" href="@Url.Content("~/Images/System/favicon.ico")" type="image/x-icon" />
    <style>
    
    </style>


    
    <!--[if lt IE 9]>
@Scripts.Render("~/Scripts/html5shiv.js")
<![endif]-->
    
   
    @Styles.Render("~/Scripts/fancybox/jquery.fancybox.css")
    @Styles.Render("~/Content/buttons.css")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
        @Styles.Render("~/Scripts/tinymce/skins/lightgray/skin.min.css")
    <link href="@Url.Content("~/Content/Reset.css")" rel="stylesheet" />
    @Scripts.Render("~/Scripts/jquery-1.8.0.min.js")
    @RenderSection("head", required: false)
    
</head>
    <body>
        @* TODO: Remove margin top *@
        <div class="wrap">
            <div class="wrapInner">
                <div class="header">
                    <div class="headerBot">
                        <div class="logo">
                            <a href="@Url.Content("~")">
                                <img src="@Url.Content("~/Images/System/logo1.png")" /></a>
                            @{ Html.RenderAction("UnderLogoMenu", "Menu"); }
                        </div>
                        @Html.Partial("./RegionSelector")
                  
                        <p style="float: left"><span>* </span>@ViewBag.Slogan</p>

                        @Html.Partial("_SearchPartial", (ViewBag.SearchViewModel != null ? new SearchViewModel() { Name = ViewBag.SearchViewModel.Name, Category = ViewBag.SearchViewModel.Category, OnlyByName = ViewBag.SearchViewModel.OnlyByName } : (new SearchViewModel() { Category = selectedSiteCategory } )))

                        @Html.Partial("_LoginMenuPartial")


                        <div class="hMenu">
                            <img class="hMenuL" src="/Images/System/hMenuL.png" />
                            <img class="hMenuR" src="/Images/System/hMenuR.png" />
                            <table>
                                <tr>
                                    <td @((selectedSiteCategory == CategorySearch.Product) ? "class=a" : "")>@Html.ActionLink("Товары", "Index", "Catalog")</td>
                                    <td @((selectedSiteCategory == CategorySearch.Realty) ? "class=a" : "")><a href="http://jay.reklama.tm/">Недвижимость</a></td>
                                    <td @((selectedSiteCategory == CategorySearch.Announcement) ? "class=a" : "")>@Html.ActionLink("Объявления", "List", "Announcement")</td>
                                    <td @((selectedSiteCategory == CategorySearch.Auto) ? "class=a" : "")>@Html.ActionLink("Авто", "List", "Announcement", new { SectionId = 3 }, null)</td>
                                    <td @((selectedSiteCategory == CategorySearch.Article) ? "class=a" : "")>@Html.ActionLink("Статьи", "Index", "Article", new{v = "1"}, new {})</td>
                                    @*<td class="f"><a href="javascript:void(0)">Форум</a></td>*@
                                </tr>
                            </table>
                        </div>


                        @* Выпадающий список с меню *@
                        @{ Html.RenderAction("AllsDropDownMenu", "Menu"); }

                    </div>
                </div>
                <div class="middle">
                    <div class="backTop" style="display: block;"><a title="Вверх" href="javascript:void(0)"></a></div>

                    @if (TempData["notice"] != null)
                    {
                        <div id="notice" style="width: 40%; margin: 10px auto; border: 1px solid green; padding: 20px; font-family: sans-serif; font-size: 14px; font-weight: bold; color: orangered;">
                            @Html.Raw(TempData["notice"])
                        </div>
                    }

                    @if (TempData["error"] != null)
                    {
                        <div id="error" style="width: 40%; margin: 10px auto; border: 1px solid red; padding: 20px; font-family: sans-serif; font-size: 12px; font-weight: bold; color: mediumblue;">
                            @Html.Raw(TempData["error"])
                        </div>
                    }

                    @RenderBody()

                </div>
                <div class="clear"></div>
            </div>

            <div class="footerOuter">
                <div class="footer">
                    <div class="footerTop"></div>
                    <div class="bMenu">
                        <table>
                            <tr>
                                <td>@Html.ActionLink("Товары", "Index", "Catalog")</td>
                                <td><a href="http://jay.reklama.tm/">Недвижимость</a></td>
                                <td>@Html.ActionLink("Объявления", "List", "Announcement")</td>
                                <td>@Html.ActionLink("Авто", "List", "Announcement", new { SectionId = 3 }, null)</td>
                                <td>@Html.ActionLink("Статьи", "Index", "Article")</td>
                                @*<td><a href="javascript:void(0)">Форум</a></td>*@
                            </tr>
                        </table>
                    </div>
                    <div class="copyright">
                        <div class="bLogo">
                            <a href="@Url.Content("~")">
                                <img src="/Images/System/logo1.png" /></a>
                        </div>
                        <p>www.reklama.tm</p>
                        <p>&copy; 2012</p>
                    </div>
                    <div class="footerInfo">

                        @* Footer Menu *@
                        @{ Html.RenderAction("FooterMenu", "Menu"); }

                        @*                    <div class="footerStat">
                        Вчера:
                        <span>12 300</span>
                        поданных объявлений, 
                        <span>448 147</span>
                        посещений,
                        <span>4 457 356</span>
                        просмотров страниц.
                    </div>
                    <div class="bSiteMap">
                        <a href="javascript:void(0)">Карта сайта</a>
                    </div>*@

                        @* FooterBottomMenu *@
                        @try { Html.RenderAction("FooterBottomMenu", "Menu"); }
                        catch { }
                        <!-- Yandex.Metrika informer -->
                        <a href="http://metrika.yandex.ru/stat/?id=21414034&amp;from=informer"
                           target="_blank" rel="nofollow">
                            <img src="//bs.yandex.ru/informer/21414034/3_0_FF6F20FF_FF4F00FF_1_pageviews"
                                 style="width: 88px; height: 31px; border: 0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" onclick="try{Ya.Metrika.informer({i:this,id:21414034,lang:'ru'});return false}catch(e){}" /></a>
                        <!-- /Yandex.Metrika informer -->
                        @if (User.IsInRole("Administrator"))
                        {
                            @Html.ActionLink("Администраторская", "General", "Admin", null, new { @class = "error" })
                        }
                        else if (User.IsInRole("Moderator"))
                        {
                            @Html.ActionLink("Модераторская", "PageIndex", "Admin", null, new { @class = "error" })
                        }

                    </div>
                    @{ Html.RenderAction("ViewSocialLinks", "Links"); }

                    <div class="reactive">
                        <p>
                            <br />
                            <a href="javascript: void(0)">Дизайн от</a>
                        </p>
                        <a href="javascript: void(0)">
                            <img src="/Images/System/reactive.png" /></a>
                    </div>

                </div>
            </div>


        </div>
        @*    @Scripts.Render("~/bundles/jquery")*@
        
        

        <!-- Yandex.Metrika counter -->
        <script type="text/javascript">
            (function (d, w, c) {
                (w[c] = w[c] || []).push(function () {
                    try {
                        w.yaCounter21414034 = new Ya.Metrika({
                            id: 21414034,
                            webvisor: true,
                            clickmap: true,
                            trackLinks: true,
                            accurateTrackBounce: true
                        });
                    } catch (e) { }
                });

                var n = d.getElementsByTagName("script")[0],
                    s = d.createElement("script"),
                    f = function () { n.parentNode.insertBefore(s, n); };
                s.type = "text/javascript";
                s.async = true;
                s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

                if (w.opera == "[object Opera]") {
                    d.addEventListener("DOMContentLoaded", f, false);
                } else { f(); }
            })(document, window, "yandex_metrika_callbacks");
        </script>
        <noscript>
            <div>
                <img src="//mc.yandex.ru/watch/21414034" style="position: absolute; left: -9999px;" alt="" />
            </div>
        </noscript>
        <!-- /Yandex.Metrika counter -->
        @Scripts.Render("~/Scripts/jquery.mCustomScrollbar.js")
        @Scripts.Render("~/Scripts/common.js")
        @Scripts.Render("~/Scripts/jquery.textshadow.js")
        @Scripts.Render("~/Scripts/jquery.equal-height-columns.js")
        @Scripts.Render("~/Scripts/photo/jquery.mousewheel.js")
        @Scripts.Render("~/Scripts/jquery.fancybox.js")
        @Scripts.Render("~/Scripts/reactive.js")
        @Scripts.Render("/Scripts/slides.min.jquery.js")
    @*Scripts.Render("~/bundles/angular-file-uploader")*@
        @Scripts.Render("~/Scripts/angular/es5-shim.min.js")
        @Scripts.Render("~/Scripts/angular/angular.min.js")
        @Scripts.Render("~/Scripts/angular/angular-file-upload.js")
        @Scripts.Render("~/Scripts/angular/controllers.js")
        @Scripts.Render("~/Scripts/angular/directives.js")
        @Scripts.Render("~/Scripts/Search.js")
        <script src="@Url.Content("~/Scripts/regionSections.js")" type="text/javascript"></script>
        @RenderSection("scripts", required: false)


    </body>


</html>

Reklama/Views/Shared/_RegistrationPartial.cshtml
@using CaptchaMvc.HtmlHelpers
@model Reklama.Models.ViewModels.Shared.RegisterModel

<div class="windowTitle">Регистрация пользователя</div> 
<div class="regBlock">
    @using (Html.BeginForm("Register", "Account", FormMethod.Post, new { id = "RegistrationForm" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <ul>
@*            <li>
                <label for="regName">Имя:</label>
                <input type="text" id="regName" name="regName" />
            </li>*@
            <li>
                @Html.LabelFor(m => m.Email)
                @Html.EditorFor(m => m.Email)<br />
                @Html.ValidationMessageFor(m => m.Email)
            </li>
            <li> 
                @Html.LabelFor(m => m.Password)
                @Html.PasswordFor(m => m.Password)<br />
                @Html.ValidationMessageFor(m => m.Password)
            </li>
            <li>
                @Html.LabelFor(m => m.ConfirmPassword)
                @Html.PasswordFor(m => m.ConfirmPassword)<br />
                @Html.ValidationMessageFor(m => m.ConfirmPassword)
                <p class="sure"><span>*</span> Заполнение всех полей обязательно</p>
            </li>
            <li>
                @Html.Captcha(5, "_CaptchaPartial")
            </li>
            <li>
                <input type="checkbox" class="AcceptUserAgreement" value="Accept" style="width: auto; float: none; height: auto; margin-top: 0;" />
                <span style="font-size: 12px;">Принимаю условия @{ Html.RenderAction("LinkToOneOfMainConfigPage", "Links", new { mainPageName = "UserAgreement" }); }</span>
                <br />
                <span class="spanUserAgreement field-validation-error unvisible">
                    Ознакомьтесь и примите условия пользовательского соглашения
                </span>
            </li>
        </ul>
        
        
        
        
        <div class="regSub">
            <input type="submit" name="regSubmit" value=" " />
        </div>
    }
</div>
<div class="regComplete">
    <span>Для завершеня регистрации необходимо активировать учетную запись.</span>
    <p>Письмо с кодом активации выслано на <a href="javascript:void(0)">mail@mail.ru</a></p>
</div>

<script type="text/javascript">
    $('#RegistrationForm').bind('submit', function () {
        var isAccept = $('.AcceptUserAgreement').is(':checked');

        if(!isAccept) {
            $('.spanUserAgreement').addClass('visible').removeClass('unvisible');
            return false;
        }
        
        $('.spanUserAgreement').addClass('unvisible').removeClass('visible');
        return true;
    });
</script>