Reklama/Models/Articles/ArticleCommentModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Entity.Articles;
using Domain.Repository.Articles;
using Reklama.Models.Shared;

namespace Reklama.Models.Articles
{
    public class ArticleCommentModel: BaseModel<ArticleComment>, IArticleCommentRepository
    {
    }
}

Reklama/Models/Articles/ArticleModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Entity.Articles;
using Domain.Repository.Articles;
using Reklama.Models.Shared;

namespace Reklama.Models.Articles
{
    public class ArticleModel: BaseModel<Article>, IArticleRepository
    {
        public IEnumerable<Article> GetBestToday4Articles()
        {
            return GetTodayArticlesQuery().OrderByDescending(a => a.ViewsCount).Take(4);
        }

        public IEnumerable<Article> GetBestToday4ArticlesBySubsection(int subsectionId)
        {
            return GetTodayArticlesQuery().Where(a => a.SubsectionId == subsectionId)
                .OrderByDescending(a => a.ViewsCount).Take(4);
        }

        protected IQueryable<Article> GetTodayArticlesQuery()
        {
            return Read().Where(
                a => a.CreatedAt.Year == DateTime.Today.Year
                    && a.CreatedAt.Month == DateTime.Today.Month
                    && a.CreatedAt.Day == DateTime.Today.Day
                );
        }

        public IQueryable<Article> ReadByDate()
        {
            return Read().OrderByDescending(a => a.CreatedAt);
        }


        public void IncrementViewsCount(Article article)
        {
            article.ViewsCount++;
            Save(article);
        }

        public IQueryable<Article> ReadLastArticle()
        {
            return ReadByDate().Take(4);
        }


        public override IQueryable<Article> Read()
        {
            return base.Read().Where(a => a.IsActive).OrderByDescending(a => a.Id);
        }


        public IQueryable<Article> ReadInactive()
        {
            return base.Read().Where(a => !a.IsActive);
        }
    }
}

Reklama/Models/Articles/ArticleSectionModel.cs
using Domain.Entity.Articles;
using Domain.Repository.Articles;
using Reklama.Models.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Reklama.Models.Articles
{
    public class ArticleSectionModel : BaseModel<ArticleSection>, IArticleSectionRepository
    {
        public ArticleSection ReadByName(string name)
        {
            return Context.Set<ArticleSection>().First(s => s.Name.Equals(name));
        }
    }
}

Reklama/Models/Articles/ArticleSubsectionModel.cs
using Domain.Entity.Articles;
using Domain.Repository.Articles;
using Reklama.Models.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Reklama.Models.Articles
{
    public class ArticleSubsectionModel : BaseModel<ArticleSubsection>, IArticleSubsectionRepository
    {
        public ArticleSubsection ReadByName(string name)
        {
            return Context.Set<ArticleSubsection>().Include("Section").First(ss => ss.Name.Equals(name));
        }

        public IQueryable<ArticleSubsection> ReadBySection(int sectionId)
        {
            return
                from s in Context.Set<ArticleSubsection>().Include("Section") 
                where s.SectionId.Equals(sectionId) 
                orderby s.Name 
                select s;
        }


        public IEnumerable<ArticleSubsection> ReadLimit(int sectionId, int limit)
        {
            return Context.Set<ArticleSubsection>().Include("Section").Where(s => s.SectionId == sectionId).Take(limit).ToArray();
        }
    }
}

Reklama/Models/SortModels/Article/ArticleSortModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Reklama.Models.SortModels.Article
{
    public class ArticleSortModel: PagerSortModel
    {
        public int? SubsectionId { get; set; }

        public ArticleSortModel()
        {
            SubsectionId = null;
        }
    }
}

Reklama/ViewModels/Catalog/DetailsViewModel.cs
using System.Collections.Generic;
using System.Linq;
using WebMatrix.WebData;

namespace Reklama.ViewModels.Catalog
{
    public class DetailsViewModel
    {
        public Data.Entities.Product CurrentProduct { get; set; }
        public IEnumerable<Data.Entities.Manufacturer> Manufacturers { get; set; }

        public bool IsInBookmarks
        {
            get { return CurrentProduct.ProductBookmark.Any(q => q.UserID == WebSecurity.CurrentUserId); }
        }

        public IEnumerable<ParametersSectionViewModel> Sections { get; set; }
    }
}

Reklama/Controllers/ArticleCommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Entity.Announcements;
using Domain.Entity.Articles;
using Domain.Repository.Articles;
using Reklama.Filters;
using Reklama.Models.ViewModels.Announcement;
using WebMatrix.WebData;
using Reklama.Models;

namespace Reklama.Controllers
{
    public class ArticleCommentController : Controller
    {
        private ReklamaContext rc = new ReklamaContext();

        private readonly IArticleCommentRepository _articleCommentRepository;

        public ArticleCommentController(IArticleCommentRepository articleCommentRepository)
        {
            _articleCommentRepository = articleCommentRepository;
            _articleCommentRepository.Context = rc;
        }


        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        [InitializeSimpleMembership]
        public ActionResult Create(AnnouncementCommentViewModel commentViewModel)
        {
            if (ModelState.IsValid)
            {

                var comment = new ArticleComment()
                {
                    Id = commentViewModel.CommentId,
                    ArticleId = commentViewModel.AnnouncementId,
                    Comment = commentViewModel.Comment,
                    CreatedAt = DateTime.Now,
                    UserId = WebSecurity.CurrentUserId
                };

                try
                {
                    _articleCommentRepository.Save(comment);
                }
                catch (DataException)
                {
                    TempData["error"] = ProjectConfiguration.Get.DataErrorMessage;
                }

                return RedirectToAction("Details", "Article", new { Id = comment.ArticleId });
            }

            TempData["Comment"] = commentViewModel.Comment;
            return RedirectToAction("Details", "Article", new { Id = commentViewModel.AnnouncementId });
        }

        [Authorize(Roles = "Administrator, Moderator")]
        public ActionResult Delete(int commentId)
        {
            var articleComment = _articleCommentRepository.Read(commentId);

            if (articleComment == null)
            {
                return HttpNotFound();
            }

            try
            {
                _articleCommentRepository.Delete(articleComment);
            }
            catch
            {
                TempData["error"] = ProjectConfiguration.Get.DataErrorMessage;
            }

            return RedirectToAction("Details", "Article", new { id = articleComment.ArticleId });
        }

        protected override void Dispose(bool disposing)
        {
            rc.Dispose();
            base.Dispose(disposing);
        }
    }
}

Reklama/Controllers/BannersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Repository.Shared;
using Reklama.Data.Base;
using Reklama.Data.Entities;
using Reklama.Data.Servises;
using Reklama.Models;
using Reklama.Models.ViewModels.Banners;
using BannerTypes = Domain.Enums.BannerTypes;

namespace Reklama.Controllers
{
    public class BannersController : Controller
    {
        private string ParentController
        {
            get
            {
                return ControllerContext.ParentActionViewContext.RouteData.Values["Controller"] as string;
            }
        }

        private string ParentAction
        {
            get
            {
                return ControllerContext.ParentActionViewContext.RouteData.Values["Action"] as string;
            }
        }

        //
        // GET: /Under Filters Banner/

        private readonly BannerService _bannerService = new BannerService();

        public ActionResult GetUnderFiltersBanner()
        {
            var banner = _bannerService.GetBanner(ParentController, ParentAction, BannerTypes.UnderFilter);
            if(banner == null || banner.Images == null) return EmptyResult();

            return PartialView("Banners/_UnderFilters", new BannerViewModel
            {
                ImageUrl = banner.Images.ImagePath,
                Link = banner.Link,
                Target = "_blank"
            });
        }


        public ActionResult GetTopBanner()
        {
            var banner = _bannerService.GetBanner(ParentController, ParentAction, BannerTypes.Top);
            if (banner == null || banner.Images == null) return EmptyResult();

            return PartialView("Banners/_TopBanner", new BannerViewModel
            {
                ImageUrl = banner.Images.ImagePath,
                Link = banner.Link,
                Target = "_blank"
            });
        }

        public ActionResult GetMain1Banner()
        {
            var banner = _bannerService.GetBanner("Home", "Home", BannerTypes.Main1);
            if (banner == null || banner.Images == null) return EmptyResult();

            return PartialView("Banners/_Main1Banner", new BannerViewModel
            {
                ImageUrl = banner.Images.ImagePath,
                Link = banner.Link,
                Target = "_blank"
            });
        }

        public ActionResult GetMain2Banner()
        {
            var banner = _bannerService.GetBanner(ParentController, ParentAction, BannerTypes.Main2);
            if (banner == null || banner.Images == null)
            {
                var banner3 = _bannerService.GetBanner(ParentController, ParentAction, BannerTypes.Main3);
                if (banner3 == null || banner3.Images == null) return EmptyResult();
                return Empty23Result();
            }

            return PartialView("Banners/_Main23Banner", new BannerViewModel
            {
                ImageUrl = banner.Images.ImagePath,
                Link = banner.Link,
                Target = "_blank"
            });
        }

        public ActionResult GetMain3Banner()
        {
            var banner = _bannerService.GetBanner(ParentController, ParentAction, BannerTypes.Main3);
            if (banner == null || banner.Images == null)
            {
                var banner2 = _bannerService.GetBanner(ParentController, ParentAction, BannerTypes.Main2);
                if (banner2 == null || banner2.Images == null) return EmptyResult();
                return Empty23Result();
            }

            return PartialView("Banners/_Main23Banner", new BannerViewModel
            {
                ImageUrl = banner.Images.ImagePath,
                Link = banner.Link,
                Target = "_blank"
            });
        }

        private ActionResult EmptyResult()
        {
            return PartialView("Banners/_EmptyBanner");
        }


        private ActionResult Empty23Result()
        {
            return PartialView("Banners/_EmptyMain23Banner");
        }
    }
}

Reklama/Controllers/LinksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Entity.Admin;
using Domain.Repository.Admin;
using Domain.Repository.Other;
using Reklama.Models;


namespace Reklama.Controllers
{
    public class LinksController : Controller
    {
        private ReklamaContext rc = new ReklamaContext();

        private readonly IConfigRepository _configRepository;
        private readonly IPageRepository _pageRepository;

        public LinksController(IConfigRepository configRepository, IPageRepository pageRepository)
        {
            _configRepository = configRepository;
            _configRepository.Context = rc;

            _pageRepository = pageRepository;
            _pageRepository.Context = rc;
        }

        public ActionResult ViewSocialLinks()
        {
            ViewBag.Facebook = _configRepository.ReadByName("LinkFacebook").Value;
            ViewBag.Vk = _configRepository.ReadByName("LinkVk").Value;
            ViewBag.Twitter = _configRepository.ReadByName("LinkTwitter").Value;
            ViewBag.GooglePlus = _configRepository.ReadByName("LinkGooglePlus").Value;
            ViewBag.Odnoklassniki = _configRepository.ReadByName("LinkOdnoklassniki").Value;
            ViewBag.Mail = _configRepository.ReadByName("LinkMail").Value;
            return View();
        }


        /**
         * Отображает ссылку на одну из основных страниц, указанных в конфиге
         * (например, Пользовательское соглашение)
         */
        public ActionResult LinkToOneOfMainConfigPage(string mainPageName, string target = "_self", string cssClass = null)
        {
            try
            {
                var config = _configRepository.ReadByName(mainPageName);
                ViewBag.Page = _pageRepository.Read(Convert.ToInt32(config.Value));
                ViewBag.CssClass = cssClass;
                ViewBag.Target = target;
                return View(config);
            }
            catch
            {
                return null;
            }
        }


        protected override void Dispose(bool disposing)
        {
            rc.Dispose();
            base.Dispose(disposing);
        }
    }
}

Reklama/Views/Article/Create.cshtml
@model Domain.Entity.Articles.Article

@{
    ViewBag.Title = "Создание новой статьи";
}

<h2>Создание статьи</h2>

@using (Html.BeginForm("Create", "Article", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Article</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div>
            <span>Раздел</span>
            @Html.DropDownList("SectionId", (SelectList)ViewBag.Sections, new { @class = "SectionList" })
        </div>

        <div>
            <span>@Html.LabelFor(s => s.SubsectionId)</span>
            @if (ViewBag.Subsections == null)
            {
                <select id="SubsectionId" name="SubsectionId" disabled="disabled"></select>
            }
            else
            {
                @Html.DropDownList("SubsectionId", (SelectList)ViewBag.Subsections)
                @Html.ValidationMessageFor(s => s.SubsectionId)
            }
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SmallDescription)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.SmallDescription, new { style = "width:400px; height: 80px;" })
            @Html.ValidationMessageFor(model => model.SmallDescription)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Description, new { style = "width:800px; height: 300px;" })
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Slug)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Slug)
            @Html.ValidationMessageFor(model => model.Slug)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IsActive)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IsActive)
            @Html.ValidationMessageFor(model => model.IsActive)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Logo)
        </div>
        <div class="editor-field">
            <input type="file" name="ArticleLogo" />
            @Html.HiddenFor(model => model.Logo)
            @Html.ValidationMessageFor(model => model.Logo)
        </div>

        <p>
            <input type="submit" value="Создать" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/wysiwyg.js")
    @Scripts.Render("~/Scripts/Article.js")
}

@section head {
    @Scripts.Render("~/Scripts/ckeditor/ckeditor.js")
    @Scripts.Render("~/Scripts/ckfinder/ckfinder.js")
}

Reklama/Views/Article/Details.cshtml
@using System.Globalization
@using Domain.Entity.Articles
@using PagedList
@using Reklama
@model Domain.Entity.Articles.Article
@{
    ViewBag.Title = Model.Name;
}

<div class="catalogInner">
    <table>
        <tr>
           <td class="ci1">
               @{
                    try {
                        Html.RenderAction("RenderSections", "Article", new { subsectionId = Model.SubsectionId });
                    }
                    catch {
                        @: Unable to render the sections. Please, contact to administrator
                    }
               } 
               
               @{ Html.RenderAction("GetUnderFiltersBanner", "Banners");}

            @*
                <div class="leftActual">
                    <p>Актуальное</p>
                    <ul>
                        <li>
                            <a href="javascript:void(0)">
                                <img src="/Images/User/lAct1.jpg" />
                                SMSZombie заразил 500 тыс. Android-устройств
                            </a>
                        </li>
                        <li>
                            <a href="javascript:void(0)">
                                <img src="/Images/User/lAct1.jpg" />
                                SMSZombie заразил 500 тыс. Android-устройств
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="leftDiscus">
                    <p>Обсуждаемое</p>
                    <ul>
                        <li><a href="javascript:void(0)">Apple похвалила Lumia и Xperia arc: они не копируют iPhone</a></li>
                        <li><a href="javascript:void(0)">Samsung DV100: доступная 16-Мп камера с двумя дисплеями</a></li>
                        <li><a href="javascript:void(0)">Apple похвалила Lumia и Xperia arc: они не копируют iPhone</a></li>
                        <li><a href="javascript:void(0)">Samsung DV100: доступная 16-Мп камера с двумя дисплеями</a></li>
                    </ul>
                </div>
            </td>
            <td class="ci2">
                <img width="10" height="1" border="0" src="/Images/System/s.png" />
            </td>*@
            <td class="ci3" valign="top">
                <div class="crumbs">
                    <a href="/">Главная страница</a>
                    <span class="arr">&rarr;</span>
                    @Html.ActionLink("Статьи", "Index", "Article")
                    <span class="arr">&rarr;</span>
                    @Model.Name
                </div>
                <h1>@Model.Name</h1>
                <div class="articleText">
                    <img class="artImg" src="@string.Concat('/', ProjectConfiguration.Get.FilePaths["articles"] + Model.Logo)" />
                    <div class="mArtDate">
                        @Model.CreatedAt.ToString("D", CultureInfo.CreateSpecificCulture("ru-RU"))
                    </div>
                    @Html.Raw(Model.Description)
                    <div class="itemInfoSoc">
                        @Html.Partial("_SocialWidgetsPartial", new Reklama.Models.ViewModels.Shared.SocialWidgetsViewModel()
                            {
                                 Title = Model.Name,
                                 Description = Model.SmallDescription,
                                 ImageLink = "http://reklama.tm" + string.Concat('/', ProjectConfiguration.Get.FilePaths["articles"] + Model.Logo),
                                 Link = "http://reklama.tm" + Url.Action("Details", "Article", new { id = Model.Id })
                            })
                        @*
                        <div><a href="#">
                            <img src="/Images/System/soc1.png" /></a></div>
                        <div><a href="#">
                            <img src="/Images/System/soc2.png" /></a></div>
                        <div><a href="#">
                            <img src="/Images/System/soc3.png" /></a></div>
                        <div><a href="#">
                            <img src="/Images/System/soc4.png" /></a></div>
                        <div><a href="#">
                            <img src="/Images/System/soc5.png" /></a></div>
                        *@
						@*<span class="tell">Рассказать друзьям:</span>*@
                    </div>
                </div>

                @* List of comments *@
                    @Html.Partial("_ArticleComments", (IPagedList<ArticleComment>)ViewBag.Comments ?? new PagedList<ArticleComment>(null, 1, 1))
            </td>
        </tr>
    </table>
</div>
<div class="middleBot"></div>
@if(User.IsInRole("Administrator"))
{
    @Html.ActionLink("Редактировать", "Edit", "Article", new { id = Model.Id }, null) <br />
    @Html.ActionLink("Удалить статью", "Delete", "Article", new { id = Model.Id }, null)
}

Reklama/Views/Article/_ArticleCommentCreate.cshtml
@model Reklama.Models.ViewModels.Announcement.AnnouncementCommentViewModel
@using CaptchaMvc.HtmlHelpers

@*<script src="~/Scripts/jquery-1.7.1.min.js"></script>*@
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<div class="itemResponseAdd">
    <em>Оставить отзыв</em>
    @using (Html.BeginForm("Create", "ArticleComment", FormMethod.Post))
    {
        @Html.ValidationSummary()

        <div class="respArea">
            @Html.TextAreaFor(c => c.Comment)
        </div>
        <div class="clear"></div>
        <div class="respRules">
            <p>рекомендуем ознакомиться -</p>
            <p>
                @{ Html.RenderAction("LinkToOneOfMainConfigPage", "Links", new { mainPageName = "UserAgreement" }); }
            </p>
        </div>
        @Html.EditorFor(c => c.CommentId)
        @Html.EditorFor(c => c.AnnouncementId)
        @Html.AntiForgeryToken()
        <div class="respSubm">
            @if(User.Identity.IsAuthenticated)
            {
                <input type="submit" value="" />
            }
            else
            {
                <div class="itemNothingResponse">Для отправки комментариев необходимо @Html.ActionLink("авторизоваться", "Login", "Account", new { returnUrl = Url.Action("Details", "Article", new { id = Model.AnnouncementId }) }, null)</div>
            }
        </div>

    }
</div>

Reklama/Views/Article/_ArticleComments.cshtml
@using Reklama.Models.ViewModels.Announcement
@model PagedList.IPagedList<Domain.Entity.Articles.ArticleComment>

<div class="itemResponse">
    <div class="itemResponseHead"><span>Отзывы</span></div>
    @if (Model == null || !Model.Any())
    {
        <div class="itemNothingResponse">Отзывов пока еще никто не оставил</div>

@* Add new comment *@
        if (TempData["Comment"] == null)
        {
        @Html.Partial("_ArticleCommentCreate", new AnnouncementCommentViewModel() { AnnouncementId = (int)ViewBag.ArticleId })
        }
        else
        {
        @Html.Partial("_ArticleCommentCreate", new AnnouncementCommentViewModel() { AnnouncementId = (int)ViewBag.ArticleId, Comment = TempData["Comment"].ToString() })
        }
    }
    else
    {

        for (int i = 0; i < Model.Count; i++)
        {
            string classGray = "itemResponseBlock gray";
            string classBlock = "itemResponseBlock";


            <div class="@((i % 2 == 0) ? @classGray : @classBlock)">
                <div class="itemResponseBlockL">
                    <img src="@((Model.ElementAt(i).UserProfile.AvatarLink != null) ? "/Images/Users/Avatars/" + Model.ElementAt(i).UserProfile.AvatarLink : "/Images/System/userAv.png")" class="avatar" />
                </div>
                <div class="itemResponseBlockR">
                    <span>
                        @Html.ActionLink(
                 string.Format("{0} {1}", Model.ElementAt(i).UserProfile.Surname ?? "",
                 Model.ElementAt(i).UserProfile.Name == null || Model.ElementAt(i).UserProfile.Name == "" ? Model.ElementAt(i).UserProfile.Email : Model.ElementAt(i).UserProfile.Name),
                            "Index", "Profile", new { id = Model.ElementAt(i).UserId }, null)
                        @string.Format("{0:dd.MM.yyyy}", @Model.ElementAt(i).CreatedAt)
                    </span>
                    <p>@Model.ElementAt(i).Comment</p>
                    @if (User.IsInRole("Administrator") || User.IsInRole("Moderator"))
                    {
                        <p>
                            @Html.ActionLink("Удалить", "Delete", "ArticleComment", new { commentId = @Model.ElementAt(i).Id }, null)
                        </p>
                    }
                </div>
            </div>
            <div class="clear"></div>
        }
                             
        
        
@* Add new comment *@
        if (TempData["Comment"] == null)
        {
        @Html.Partial("_ArticleCommentCreate", new AnnouncementCommentViewModel() { AnnouncementId = (int)ViewBag.ArticleId })
        }
        else
        {
        @Html.Partial("_ArticleCommentCreate", new AnnouncementCommentViewModel() { AnnouncementId = (int)ViewBag.ArticleId, Comment = TempData["Comment"].ToString() })
        }
        
        
        
        
        
        <div class="pages">
            <ul class="fastNav">
                <img class="fastNavL" src="/Images/System/fastNavL.png" />
                <img class="fastNavR" src="/Images/System/fastNavR.png" />
                <a class="page-prev" href="javascript:void(0)"></a>
                

                @for (int page = 1; page <= Model.PageCount && page <= 7; page++)
                {
                    <li>

                        @if (page == Model.PageNumber)
                        {
                            @Html.ActionLink(page.ToString(), "Details", new
                                                                             {
                                                                                 id = (int)ViewBag.ArticleId,
                                                                                 commentPage = page
                                                                             },
                                             new { @class = "hr" })
                        }
                        else
                        {
                            @Html.ActionLink(page.ToString(), "Details", new
                                                                             {
                                                                                 id = (int)ViewBag.ArticleId,
                                                                                 commentPage = page
                                                                             })
                        }
                    </li>
                }
                
                @if (Model.PageCount > 14)
                        {
                            <li class="exppages"><a class="exppagesTitle" href="javascript:void(0)">все<img src="/Images/System/orArrow.png" /></a>
                            </li>
                        }
                
                @for (int page = Model.PageCount - 6; page <= Model.PageCount && page > 7; page++)
                {
                    <li>

                        @if (page == Model.PageNumber)
                        {
                            @Html.ActionLink(page.ToString(), "Details", new
                                                                             {
                                                                                 id = (int)ViewBag.ArticleId,
                                                                                 commentPage = page
                                                                             },
                                             new { @class = "hr" })
                        }
                        else
                        {
                            @Html.ActionLink(page.ToString(), "Details", new
                                                                             {
                                                                                 id = (int)ViewBag.ArticleId,
                                                                                 commentPage = page
                                                                             })
                        }
                    </li>
                }
                <a class="page-next" href="javascript:void(0)"></a>
            </ul>

            <div class="pageslider">
                <div class="pagesliderTop">
                    <ul>
                        @for (int page = 1; page <= Model.PageCount; page++)
                        {
                            <li>

                                @if (page == Model.PageNumber)
                                {
                                    @Html.ActionLink(page.ToString(), "Details", new
                                                                                     {
                                                                                         id = (int)ViewBag.ArticleId,
                                                                                         commentPage = page
                                                                                     },
                                                     new { @class = "shr" })
                                }
                                else
                                {
                                    @Html.ActionLink(page.ToString(), "Details", new
                                                                                     {
                                                                                         id = (int)ViewBag.ArticleId,
                                                                                         commentPage = page
                                                                                     })
                                }
                            </li>
                        }
                    </ul>
                </div>
                @*<div class="alHScrollBar">
                    <div class="alHScrollSlider" style="left: 0px;"></div>
                </div>*@
            </div>
        </div>
        
        
        
    }
</div>

@section head
{
    @Styles.Render("~/Content/Profile.css")
}