Reklama/Models/Realty/RealtyBookmarkModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Entity.Realty;
using Domain.Repository.Realty;
using Reklama.Models.Shared;

namespace Reklama.Models.Realty
{
    public class RealtyBookmarkModel: BaseModel<RealtyBookmark>, IRealtyBookmarkRepository
    {
        public IQueryable<RealtyBookmark> ReadByUser(int userId)
        {
            return Context.Set<RealtyBookmark>().Where(r => r.UserId == userId);
        }

        public IQueryable<Domain.Entity.Realty.Realty> ReadRealtyByUser(int userId)
        {
            return from a in Context.Set<RealtyBookmark>()
                .Include("Realty")
                .Include("UserProfile")
                   where a.UserId.Equals(userId)
                   orderby a.Id descending
                   select a.Realty;
        }

        public bool IsIsset(int userId, int realtyId)
        {
            return Read().Any(a => a.RealtyId.Equals(realtyId) && a.UserId.Equals(userId));
        }

        public RealtyBookmark Read(int userId, int realtyId)
        {
            return Context.Set<RealtyBookmark>()
                .Include("Realty")
                .Include("UserProfile")
                .Single(a => a.RealtyId.Equals(realtyId) && a.UserId.Equals(userId));
        }
    }
}

Reklama/Models/Realty/RealtyCategoryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Entity.Realty;
using Domain.Repository.Realty;
using Reklama.Models.Shared;

namespace Reklama.Models.Realty
{
    public class RealtyCategoryModel: BaseModel<RealtyCategory>, IRealtyCategoryRepository
    {
    }
}

Reklama/Models/Realty/RealtyFeedbackModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Repository.Realty;
using Domain.Entity.Realty;
using Reklama.Models.Shared;

namespace Reklama.Models.Realty
{
    public class RealtyFeedbackModel: BaseModel<RealtyComment>, IRealtyCommentRepository
    {
        public IQueryable<RealtyComment> ReadByUser(int userId)
        {
            return Context.Set<RealtyComment>().Where(r => r.UserId == userId);
        }

        public IQueryable<RealtyComment> ReadByRealty(int realtyId)
        {
            return Context.Set<RealtyComment>().Where(r => r.RealtyId == realtyId);
        }
    }
}

Reklama/Controllers/LinksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Entity.Admin;
using Domain.Repository.Admin;
using Domain.Repository.Other;
using Reklama.Models;


namespace Reklama.Controllers
{
    public class LinksController : Controller
    {
        private ReklamaContext rc = new ReklamaContext();

        private readonly IConfigRepository _configRepository;
        private readonly IPageRepository _pageRepository;

        public LinksController(IConfigRepository configRepository, IPageRepository pageRepository)
        {
            _configRepository = configRepository;
            _configRepository.Context = rc;

            _pageRepository = pageRepository;
            _pageRepository.Context = rc;
        }

        public ActionResult ViewSocialLinks()
        {
            ViewBag.Facebook = _configRepository.ReadByName("LinkFacebook").Value;
            ViewBag.Vk = _configRepository.ReadByName("LinkVk").Value;
            ViewBag.Twitter = _configRepository.ReadByName("LinkTwitter").Value;
            ViewBag.GooglePlus = _configRepository.ReadByName("LinkGooglePlus").Value;
            ViewBag.Odnoklassniki = _configRepository.ReadByName("LinkOdnoklassniki").Value;
            ViewBag.Mail = _configRepository.ReadByName("LinkMail").Value;
            return View();
        }


        /**
         * Отображает ссылку на одну из основных страниц, указанных в конфиге
         * (например, Пользовательское соглашение)
         */
        public ActionResult LinkToOneOfMainConfigPage(string mainPageName, string target = "_self", string cssClass = null)
        {
            try
            {
                var config = _configRepository.ReadByName(mainPageName);
                ViewBag.Page = _pageRepository.Read(Convert.ToInt32(config.Value));
                ViewBag.CssClass = cssClass;
                ViewBag.Target = target;
                return View(config);
            }
            catch
            {
                return null;
            }
        }


        protected override void Dispose(bool disposing)
        {
            rc.Dispose();
            base.Dispose(disposing);
        }
    }
}

Reklama/Controllers/RealtyCommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Reklama.Models;
using Domain.Repository.Realty;
using Reklama.Filters;
using Reklama.Models.ViewModels.Realty;
using Domain.Entity.Realty;
using WebMatrix.WebData;
using System.Data;

namespace Reklama.Controllers
{
    public class RealtyCommentController : Controller
    {
        private ReklamaContext rc = new ReklamaContext();

        private readonly IRealtyCommentRepository _realtyCommentRepository;


        public RealtyCommentController(IRealtyCommentRepository realtyCommentRepository)
        {
            _realtyCommentRepository = realtyCommentRepository;
            _realtyCommentRepository.Context = rc;
        }


        [HttpPost]
        [Authorize]
        [InitializeSimpleMembership]
        public ActionResult Create(RealtyCommentViewModel commentViewModel)
        {
            if (ModelState.IsValid)
            {

                RealtyComment comment = new RealtyComment()
                                                  {
                                                      Id = commentViewModel.CommentId,
                                                      RealtyId = commentViewModel.RealtyId,
                                                      Comment = commentViewModel.Comment,
                                                      CreatedAt = DateTime.Now,
                                                      IsActive = true,
                                                      UserId = WebSecurity.CurrentUserId
                                                  };

                try
                {
                    _realtyCommentRepository.Save(comment);
                }
                catch(DataException)
                {
                    TempData["error"] = ProjectConfiguration.Get.DataErrorMessage;
                }

                return Redirect(string.Format("http://jay.reklama.tm/Details/{0}", commentViewModel.RealtyId));
            }
            else
            {
                TempData["Comment"] = commentViewModel.Comment;
                return Redirect(string.Format("http://jay.reklama.tm/Details/{0}", commentViewModel.RealtyId));
            }
        }


        [Authorize(Roles = "Administrator, Moderator")]
        public ActionResult Delete(int commentId)
        {
            var realtyComment = _realtyCommentRepository.Read(commentId);

            if (realtyComment == null)
            {
                return HttpNotFound();
            }

            try
            {
                _realtyCommentRepository.Delete(realtyComment);
            }
            catch
            {
                TempData["error"] = ProjectConfiguration.Get.DataErrorMessage;
            }

            return Redirect(string.Format("http://jay.reklama.tm/Details/{0}", realtyComment.RealtyId));
        }


        protected override void Dispose(bool disposing)
        {
            rc.Dispose();
            base.Dispose(disposing);
        }

    }
}

Reklama/Controllers/RealtyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Entity.Common;
using Domain.Entity.Realty;
using Domain.Entity.Shared;
using Domain.Repository.Admin;
using Domain.Repository.Other;
using Domain.Repository.Realty;
using Domain.Repository.Shared;
using System.IO;
using Domain.Utils;
using Reklama.Attributes;
using Reklama.Core.UploadImages;
using Reklama.Models.SortModels;
using Reklama.Services;
using WebMatrix.WebData;
using PagedList;
using Reklama.Models;
using Reklama.Models.ViewModels.Realty;
using System.Data;
using Domain.Enums;

namespace Reklama.Controllers
{
    public class RealtyController : Controller
    {
        private ReklamaContext rc = new ReklamaContext();

        //private readonly IFileService _fileService = new FileServiceStub();
        private readonly IRealtyRepository _realtyRepository;
        private readonly ICityRepository _cityRepository;
        private readonly IRealtyCategoryRepository _categoryRepository;
        private readonly IRealtySectionRepository _sectionRepository;
        private readonly ICurrencyRepository _currencyRepository;
        private readonly IRealtyPhotoRepository _photoRepository;
        private readonly IRealtyBookmarkRepository _bookmarkRepository;
        private readonly IProfileRepository _profileRepository;
        private readonly IComputerRepository _computerRepository;
        private readonly IComputerRealtyRefRepository _computerRealtyRefRepository;
        private readonly AnonymousUserService _anonymousUserService = new AnonymousUserService();

        public RealtyController(IRealtyRepository realtyRepository, ICityRepository cityRepository,
                                IRealtyCategoryRepository categoryRepository, IRealtySectionRepository sectionRepository,
                                ICurrencyRepository currencyRepository, IRealtyPhotoRepository photoRepository,
                                IRealtyBookmarkRepository bookmarkRepository, IProfileRepository profileRepository, IComputerRepository computerRepository, IComputerRealtyRefRepository computerRealtyRefRepository)
        {
            _realtyRepository = realtyRepository;
            _realtyRepository.Context = rc;

            _cityRepository = cityRepository;
            _cityRepository.Context = rc;

            _categoryRepository = categoryRepository;
            _categoryRepository.Context = rc;

            _sectionRepository = sectionRepository;
            _sectionRepository.Context = rc;

            _currencyRepository = currencyRepository;
            _currencyRepository.Context = rc;

            _photoRepository = photoRepository;
            _photoRepository.Context = rc;

            _bookmarkRepository = bookmarkRepository;
            _bookmarkRepository.Context = rc;

            _profileRepository = profileRepository;
            _profileRepository.Context = rc;

            _computerRepository = computerRepository;
            _computerRepository.Context = rc;

            _computerRealtyRefRepository = computerRealtyRefRepository;
            _computerRealtyRefRepository.Context = rc;

            ViewBag.SelectedSiteCategory = CategorySearch.Realty;
        }

        public ActionResult RedirectToSubdomain(string actionName, string id)
        {
            var url = "http://jay.reklama.tm/";
            url += actionName ?? "";
            url += id == null ? "" : "/" + id;
            return Redirect(url);
        }

        public ActionResult List(RealtySortByParams sortModel = null)
        {
            var realty = _realtyRepository.Read();
            ViewBag.Categories = _categoryRepository.Read();
            ViewBag.Cities = _cityRepository.Read();
            ViewBag.Sections = _sectionRepository.Read();
            ViewBag.SortModel = sortModel ?? new RealtySortByParams();
            if (sortModel != null && sortModel.IsEnableSort)
            {
                realty = _realtyRepository.SortByParams(realty, sortModel.CategoryId, sortModel.CityId, sortModel.FromPrice, sortModel.ToPrice, sortModel.CountsRoom,
                                                         sortModel.FromSquare, sortModel.ToSquare, sortModel.FromFloorCount, sortModel.ToFloorCount, sortModel.FromFloor,
                                                         sortModel.ToFloor, sortModel.FromCeillingHeight, sortModel.ToCeillingHeight, sortModel.WithPhoto,
                                                         sortModel.IsAuction, sortModel.IsPerson, sortModel.WithGarage, sortModel.WithGarden, sortModel.WithExtension,
                                                         sortModel.WithBasement, sortModel.Street);
            }
            realty = _realtyRepository.Sort(realty, sortModel.SortOrder, sortModel.SortOptions, sortModel.SectionId,
                                                 sortModel.CategoryId);

            return View("List", realty.ToPagedList(sortModel.CurrentPage.HasValue ? sortModel.CurrentPage.Value : 1, sortModel.PageSize));
        }

        public ActionResult SortedByParamList(RealtySortByParams sortModel)
        {
            sortModel.IsEnableSort = true;
            sortModel.CurrentPage = 1;
            return List(sortModel);
        }

        //
        // GET: /Realty/Details/5

        public ActionResult Details(int? id, int? commentPage, RealtySortByParams sortModel = null)
        {
            ViewBag.SortModel = sortModel;
            if (!id.HasValue)
            {
                return HttpNotFound();
            }

            var realty = _realtyRepository.Read(id.Value);

            if (realty == null)
            {
                return HttpNotFound();
            }

            ViewBag.IsUserCanEditRealty = _anonymousUserService.IsUserCanEditRealty(realty.Id);
            realty.Views++;
            _realtyRepository.SaveIgnoreCurrency(realty);
            ViewBag.RealtyPhotos = _photoRepository.ReadByRealty(realty.Id).ToArray();
            ViewBag.UpTimeHours = int.Parse(ProjectConfiguration.Get.GetConfigValue("UpTimeRealty").ToString());
            ViewBag.SortModel = sortModel;
            ViewBag.Categories = _categoryRepository.Read();
            ViewBag.RealtyId = realty.Id;
            ViewBag.IsIssetInBookmark = _bookmarkRepository.IsIsset(WebSecurity.CurrentUserId, realty.Id);
            ViewBag.Comments = (realty.Comments != null && realty.Comments.Count > 0)
                ? realty.Comments.ToPagedList(commentPage ?? 1, ProjectConfiguration.Get.CommentsOnPage)
                : null;

            return View(realty);
        }



        [CustomRealtyAuth]
        public ActionResult CreateMobile()
        {
            var model = new Realty();
            var userID = WebSecurity.CurrentUserId;
            if (userID != -1)
            {
                var user = _profileRepository.Read(WebSecurity.CurrentUserId);
                model.Phone = user.Phone;
                model.ContactEmail = user.Email;
                model.ContactName = user.Name;
                model.IsDisplayPhone = true;
            }

            var sections = _sectionRepository.Read();
            var categories = _categoryRepository.Read();
            ViewBag.Cities = _cityRepository.Read();
            ViewBag.Sections = sections;
            ViewBag.Categories = categories;
            ViewBag.Currencies = _currencyRepository.Read();
            ViewBag.ExpiredAt = int.Parse(ProjectConfiguration.Get.GetConfigValue("ExpiredAtRealty").ToString());

            try { model.SectionId = sections.FirstOrDefault(x => x.Name.ToLower().Contains("продам")).Id; } catch {}
            try { model.CategoryId = categories.FirstOrDefault(x => x.Name.ToLower().Contains("квартир")).Id; } catch {}
            model.Name = "empty name";
            model.SmallDescription = "empty description";
            return View("CreateMobile" ,model);
        }

        [CustomRealtyAuth]
        public ActionResult Create()
        {
            //if(!User.Identity.IsAuthenticated)
            //{
            //    return Redirect("http://reklama.tm/Account/Login?ReturnUrl=/Realty/Create");
            //}
            var model = new Realty();
            var userID = WebSecurity.CurrentUserId;
            if (userID != -1)
            {
                var user = _profileRepository.Read(WebSecurity.CurrentUserId);
                model.Phone = user.Phone;
                model.ContactEmail = user.Email;
                model.ContactName = user.Name;
                model.IsDisplayPhone = true;
            }

            ViewBag.Cities = _cityRepository.Read();
            ViewBag.Sections = _sectionRepository.Read();
            ViewBag.Categories = _categoryRepository.Read();
            ViewBag.Currencies = _currencyRepository.Read();
            ViewBag.ExpiredAt = int.Parse(ProjectConfiguration.Get.GetConfigValue("ExpiredAtRealty").ToString());
            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CreateMobile(Realty realty, FormCollection collection)
        {
            if (realty.Floor > realty.FloorCount)
            {
                ModelState.AddModelError("Floor", "Значени поля 'На каком этаже' не может превышать общего кол-ва этажей в доме");
            }
            if (realty.IsAgency == true && realty.AgencyName.Length == 0)
            {
                ModelState.AddModelError("AgencyName", "Поле 'Название агенства' обязательно для заполнения");
            }
            //ViewBag.cError = "ModelState.IsValid = ";
            ModelState.Remove("IsDisplayPhone");
            if (ModelState.IsValid)
            {
                realty.CreatedAt = realty.UpTime = DateTime.Now;
                realty.ExpiredAt = DateTime.Now.AddDays(int.Parse(ProjectConfiguration.Get.GetConfigValue("ExpiredAtRealty").ToString()));
                realty.UserId = WebSecurity.CurrentUserId;

Reklama/Views/Realty/Delete.cshtml
@model Domain.Entity.Realty.Realty

@{
    ViewBag.Title = "Удаление объявления";
}

<h2>Удаление объявления</h2>

<h3>Вы уверены, что хотите удалить объявление `@Model.Name`?</h3>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" />
    </p>
}

Reklama/Views/Realty/DeleteMobile.cshtml
@model Domain.Entity.Realty.Realty

@{
    Layout = "~/Views/_Layout/_Mobile.cshtml";
    ViewBag.Title = "Удаление объявления";
}

<div class="bg-silver">
    <div class="main-header">
        <div class="btn-panel mb-2 mt-2 d-inline-block">
        </div>
    </div>
    <div class="main-container">
        <div class="card mt-1 mr-3 ml-3">
            <div class="card-header">
                Удаление объявления
                <i class="fa fa-exclamation"></i>
            </div>
            <div class="card-body">
                <h5>Вы уверены, что хотите удалить объявление `@Model.Name`?</h5>
                @using (Html.BeginForm("DeleteConfirmedMobile", "Realty", new { id = Model.Id }, FormMethod.Get, null))
                {
                    <button type="submit" class="btn btn-large btn-danger"><i class="fa fa-check"></i> Удалить</button>
                    <a href="@Url.Action("MyAnnouncementsMobile","Bookmarks")" class="btn btn-large btn-secondary"><i class="fa fa-times"></i> Отмена</a>
                }
            </div>
        </div>

    </div>
</div>

Reklama/Views/Realty/PlayStopMobile.cshtml
@model Domain.Entity.Realty.Realty

@{
    Layout = "~/Views/_Layout/_Mobile.cshtml";
    ViewBag.Title = "Включить/выключить объявления";
}

<div class="bg-silver">
    <div class="main-header">
        <div class="btn-panel mb-2 mt-2 d-inline-block">
        </div>
    </div>
    <div class="main-container">
        <div class="card mt-1 mr-3 ml-3">
            <div class="card-header">
                Включить/выключить объявления
                <i class="fa fa-exclamation"></i>
            </div>
            <div class="card-body">
                <h5>Вы уверены, что хотите @(Model.IsActive ? "отключить " : "включить " ) объявление `@Model.Name`?</h5>
                @using (Html.BeginForm("PlayStopConfirmedMobile", "Realty", new { id = Model.Id }, FormMethod.Get, null))
                {
                    <button type="submit" class="btn btn-large btn-primary"><i class="fa fa-check"></i> ОК</button>
                    <a href="@Url.Action("MyAnnouncementsMobile","Bookmarks")" class="btn btn-large btn-secondary"><i class="fa fa-times"></i> Отмена</a>
                }
            </div>
        </div>

    </div>
</div>

Reklama/Views/Realty/_RealtyCategories.cshtml
@using Reklama.Models.ViewModels.Realty
@model IQueryable<Domain.Entity.Realty.RealtyCategory>

@{ 
    var sortModel = (RealtySortByParams)ViewBag.SortModel;
}
<span class="hed0">Категории недвижимости:</span>
@*<span class="hed1">@Html.ActionLink("Все разделы", "Catalog", "Realty", null, new { @class = "allSectionsLink" })</span>*@
<div class="lMenu">
    <ul>
        @foreach (var category in Model)
        {
            <li><span>@Html.ActionLink(category.Name, "List", new
                 {
                     SortOptions = sortModel.SortOptions,
                     SortOrder = sortModel.SortOrder,
                     IsEnableSort = sortModel.IsEnableSort,
                     CurrentPage = 1,
                     PageSize = sortModel.PageSize,
                     CategoryId = category.Id,
                     SectionId = sortModel.SectionId,
                     CityId = sortModel.CityId,
                     sortModel.StringCountsRoom,
                     IsAuction = sortModel.IsAuction,
                     IsPerson = sortModel.IsPerson,
                     Street = sortModel.Street,
                     WithBasement = sortModel.WithBasement,
                     WithExtension = sortModel.WithExtension,
                     WithGarage = sortModel.WithGarage,
                     WithGarden = sortModel.WithGarden,
                     WithPhoto = sortModel.WithPhoto,
                     ToCeillingHeight = sortModel.ToCeillingHeight,
                     FromCeillingHeight = sortModel.FromCeillingHeight,
                     ToFloor = sortModel.ToFloor,
                     FromFloor = sortModel.FromFloor,
                     ToFloorCount = sortModel.ToFloorCount,
                     FromFloorCount = sortModel.FromFloorCount,
                     ToPrice = sortModel.ToPrice,
                     FromPrice = sortModel.FromPrice,
                     ToSquare = sortModel.ToSquare,
                     FromSquare = sortModel.FromSquare
                 })
            </span>
            </li>
        }
    </ul>
</div>

Reklama/Views/Realty/_RealtyCommentCreate.cshtml
@model Reklama.Models.ViewModels.Realty.RealtyCommentViewModel
@using CaptchaMvc.HtmlHelpers

@*<script src="~/Scripts/jquery-1.7.1.min.js"></script>*@
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<div class="itemResponseAdd">
    <em>Оставить отзыв</em>
    @using (Html.BeginForm("Create", "RealtyComment", FormMethod.Post))
    {
        @Html.ValidationSummary()

        <div class="respArea">
            @Html.TextAreaFor(c => c.Comment)
        </div>
        <div class="clear"></div>
        <div class="respRules">
            <p>рекомендуем ознакомиться -</p>
            <p>
                @{ Html.RenderAction("LinkToOneOfMainConfigPage", "Links", new { mainPageName = "UserAgreement" }); }
            </p>
        </div>
        @Html.EditorFor(c => c.CommentId)
        @Html.EditorFor(c => c.RealtyId)
        <div class="respSubm">
            @if(User.Identity.IsAuthenticated)
            {
                <input type="submit" value="" />
            }
            else
            {
                <div class="itemNothingResponse">Для отправки комментариев необходимо @Html.ActionLink("авторизоваться", "Login", "Account", new { returnUrl = Url.Action("Details", "Realty", new { id = Model.RealtyId }) }, null)</div>
            }
        </div>

    }
</div>

Reklama/Views/Realty/_RealtyComments.cshtml
@using Reklama.Models.ViewModels.Realty
@model PagedList.IPagedList<Domain.Entity.Realty.RealtyComment>

<div class="itemResponse">
    <div class="itemResponseHead"><span>Отзывы</span></div>
    @if (!Model.Any())
    {
        <div class="itemNothingResponse">Отзывов пока еще никто не оставил</div>

@* Add new comment *@
        if (TempData["Comment"] == null)
        {
            @Html.Partial("_RealtyCommentCreate", new RealtyCommentViewModel() { RealtyId = (int)ViewBag.RealtyId })
        }
        else
        {
            @Html.Partial("_RealtyCommentCreate", new RealtyCommentViewModel() { RealtyId = (int)ViewBag.RealtyId, Comment = TempData["Comment"].ToString() })
        }
    }
    else
    {

        for (int i = 0; i < Model.Count; i++)
        {
            string classGray = "itemResponseBlock gray";
            string classBlock = "itemResponseBlock";


        <div class="@((i % 2 == 0) ? @classGray : @classBlock)">
            <div class="itemResponseBlockL">
                <img src="@((Model.ElementAt(i).UserProfile.AvatarLink != null) ? "/Images/Users/Avatars/" + Model.ElementAt(i).UserProfile.AvatarLink : "/Images/System/userAv.png")" class="avatar" />
            </div>
            <div class="itemResponseBlockR">
                <span>
                    @Html.ActionLink(
                 string.Format("{0} {1}", Model.ElementAt(i).UserProfile.Surname ?? "",
                 Model.ElementAt(i).UserProfile.Name == null || Model.ElementAt(i).UserProfile.Name == "" ? Model.ElementAt(i).UserProfile.Email : Model.ElementAt(i).UserProfile.Name),
                            "Index", "Profile", new { id = Model.ElementAt(i).UserId }, null)
                    @string.Format("{0:dd.MM.yyyy}", @Model.ElementAt(i).CreatedAt)
                </span>
                <p>@Model.ElementAt(i).Comment</p>

                @if(User.IsInRole("Administrator") || User.IsInRole("Moderator")) {
                    <p>
                        @Html.ActionLink("Удалить", "Delete", "RealtyComment", new { commentId = @Model.ElementAt(i).Id }, null)
                    </p>
                }
            </div>
        </div>
        <div class="clear"></div>
        }
                             
        
        
@* Add new comment *@
        if (TempData["Comment"] == null)
        {
            @Html.Partial("_RealtyCommentCreate", new RealtyCommentViewModel() { RealtyId = (int)ViewBag.RealtyId })
        }
        else
        {
            @Html.Partial("_RealtyCommentCreate", new RealtyCommentViewModel() { RealtyId = (int)ViewBag.RealtyId, Comment = TempData["Comment"].ToString() })
        }
        
        
        
        
        
        <div class="pages">
            <ul class="fastNav">
                <img class="fastNavL" src="/Images/System/fastNavL.png" />
                <img class="fastNavR" src="/Images/System/fastNavR.png" />
                <a class="page-prev" href="javascript:void(0)"></a>

                @for (int page = 1; page <= Model.PageCount && page <= 7; page++)
                {
                    <li>

                        @if (page == Model.PageNumber)
                        {
                            @Html.ActionLink(page.ToString(), "Details", new
                                                                             {
                                                                                 id = (int)ViewBag.RealtyId,
                                                                                 commentPage = page
                                                                             },
                                             new { @class = "hr" })
                        }
                        else
                        {
                            @Html.ActionLink(page.ToString(), "Details", new
                                                                             {
                                                                                 id = (int)ViewBag.RealtyId,
                                                                                 commentPage = page
                                                                             })
                        }
                    </li>
                }
                
                @if (Model.PageCount > 14)
                        {
                            <li class="exppages"><a class="exppagesTitle" href="javascript:void(0)">все<img src="/Images/System/orArrow.png" /></a>
                            </li>
                        }
                
                @for (int page = Model.PageCount - 6; page <= Model.PageCount && page > 7; page++)
                {
                    <li>

                        @if (page == Model.PageNumber)
                        {
                            @Html.ActionLink(page.ToString(), "Details", new
                                                                             {
                                                                                 id = (int)ViewBag.RealtyId,
                                                                                 commentPage = page
                                                                             },
                                             new { @class = "hr" })
                        }
                        else
                        {
                            @Html.ActionLink(page.ToString(), "Details", new
                                                                             {
                                                                                 id = (int)ViewBag.RealtyId,
                                                                                 commentPage = page
                                                                             })
                        }
                    </li>
                }

                <a class="page-next" href="javascript:void(0)"></a>
            </ul>

            <div class="pageslider">
                <div class="pagesliderTop">
                    <ul>
                        @for (int page = 1; page <= Model.PageCount; page++)
                        {
                            <li>

                                @if (page == Model.PageNumber)
                                {
                                    @Html.ActionLink(page.ToString(), "Details", new
                                                                                     {
                                                                                         id = (int)ViewBag.RealtyId,
                                                                                         commentPage = page
                                                                                     },
                                                     new { @class = "shr" })
                                }
                                else
                                {
                                    @Html.ActionLink(page.ToString(), "Details", new
                                                                                     {
                                                                                         id = (int)ViewBag.RealtyId,
                                                                                         commentPage = page
                                                                                     })
                                }
                            </li>
                        }
                    </ul>
                </div>
                @*<div class="alHScrollBar">
                    <div class="alHScrollSlider" style="left: 0px;"></div>
                </div>*@
            </div>
        </div>
        
        
        
    }
</div>

@section head
{
    @Styles.Render("~/Content/Profile.css")
}