Reklama/Models/Catalog/CatalogCategoryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Entity.Catalogs;
using Domain.Repository.Catalogs;
using Reklama.Models.Shared;

namespace Reklama.Models.Catalog
{
    public class CatalogCategoryModel: BaseModel<CatalogCategory>, ICatalogCategoryRepository
    {
    }
}

Reklama/Models/Catalog/CatalogParamSubsectionModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Entity.Catalogs;
using Domain.Repository.Catalogs;
using Reklama.Models.Shared;

namespace Reklama.Models.Catalog
{
    public class CatalogParamSubsectionModel: BaseModel<CatalogParamSubsection>, ICatalogParamSubsectionRepository
    {
    }
}

Reklama/Models/Catalog/CatalogSecondCategoryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Entity.Catalogs;
using Domain.Repository.Catalogs;
using Reklama.Models.Shared;

namespace Reklama.Models.Catalog
{
    public class CatalogSecondCategoryModel: BaseModel<CatalogSecondCategory>, ICatalogSecondCategoryRepository
    {
        public IQueryable<CatalogSecondCategory> ReadByCategory(int categoryId)
        {
            return ((ReklamaContext) Context).CatalogSecondCategories.Where(c => c.CategoryId == categoryId);
        }
    }
}

Reklama/Models/Catalog/CatalogThirdCategoryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Entity.Catalogs;
using Domain.Repository.Catalogs;
using Reklama.Models.Shared;

namespace Reklama.Models.Catalog
{
    public class CatalogThirdCategoryModel: BaseModel<CatalogThirdCategory>, ICatalogThirdCategoryRepository
    {
        public IQueryable<CatalogThirdCategory> ReadBySecondCategory(int category2Id)
        {
            return ((ReklamaContext) Context).CatalogThirdCategories.Where(a => a.SecondCategoryId == category2Id);
        }
    }
}

Reklama/Models/Catalog/ProductBookmarkModel.cs
using Domain.Entity.Catalogs;
using Domain.Repository.Catalogs;
using Reklama.Models.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Reklama.Models.Catalog
{
    public class ProductBookmarkModel : BaseModel<ProductBookmark>, IProductBookmarkRepository
    {
        public IQueryable<Product> ReadProductsByUser(int userId)
        {
            return from a in Context.Set<ProductBookmark>()
                .Include("Product")
                .Include("UserProfile")
                   where a.UserId.Equals(userId)
                   orderby a.Id descending
                   select a.Product;
        }

        public bool IsIsset(int userId, int productId)
        {
            return Read().Any(a => a.ProductId.Equals(productId) && a.UserId.Equals(userId));
        }

        public ProductBookmark Read(int userId, int productId)
        {
            return Context.Set<ProductBookmark>()
                .Include("Product")
                .Include("UserProfile")
                .Single(a => a.ProductId.Equals(productId) && a.UserId.Equals(userId));
        }
    }
}

Reklama/Models/Catalog/ProductFeedbackModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Entity.Catalogs;
using Domain.Repository.Catalogs;
using Reklama.Models.Shared;

namespace Reklama.Models.Catalog
{
    public class ProductFeedbackModel: BaseModel<ProductFeedback>, IProductFeedbackRepository
    {
    }
}

Reklama/Models/Catalog/ProductImageModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Entity.Catalogs;
using Domain.Repository.Catalogs;
using Reklama.Models.Shared;

namespace Reklama.Models.Catalog
{
    public class ProductImageModel: BaseModel<ProductImage>, IProductImageRepository
    {
        public void Delete(int id, string image)
        {
            var imageWithoutPath = image.Split(new[] { '/' }, StringSplitOptions.RemoveEmptyEntries).Last();
            var productImage =
                Context.Set<ProductImage>().Where(p => p.ProductId == id).First(
                    a => a.Link.Equals(imageWithoutPath));
            Delete(productImage);
        }
    }
}

Reklama/Models/Catalog/ProductModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Entity.Catalogs;
using Domain.Repository.Catalogs;
using Reklama.Models.Shared;
using Domain.Enums;

namespace Reklama.Models.Catalog
{
    public class ProductModel: BaseModel<Product>, IProductRepository
    {
        public IQueryable<Product> ReadBySecondCategory(int secondCategoryId)
        {
            return ReadActivesQuery().Where(p => p.SecondCategoryId == secondCategoryId);
        }

        public IQueryable<Product> ReadByThirdCategory(int thirdCategoryId)
        {
            return ReadActivesQuery().Where(p => p.ThirdCategoryId == thirdCategoryId);
        }

        public IQueryable<Product> ReadActivesQuery()
        {
            return Context.Set<Product>().Where(p => p.IsActive == true);
        }


        public IQueryable<Product> Sort(IQueryable<Product> products, SortOrderParams sortOrder, SortOptionsParams sortOptions, 
            int secondCategoryId, int? thirdCategoryId)
        {

            if (thirdCategoryId.HasValue)
            {
                products = products.Where(p => p.ThirdCategoryId == thirdCategoryId.Value);
            }

            if (sortOrder == SortOrderParams.Ascending)
            {
                if (sortOptions == SortOptionsParams.ByName)
                {
                    products = products.OrderBy(p => p.Name);
                }
                else
                {
                    products = products.OrderBy(p => p.ShopProductRefs.Min(spr => spr.Price));
                }
            }
            // Sorting by descending
            else
            {
                if (sortOptions == SortOptionsParams.ByName)
                {
                    products = products.OrderByDescending(p => p.Name);
                }
                else
                {
                    products = products.OrderByDescending(p => p.ShopProductRefs.Max(spr => spr.Price));
                }
            }

            return products;
        }
    }
}

Reklama/Models/Catalog/ProductParamModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Entity.Catalogs;
using Domain.Repository.Catalogs;
using Reklama.Models.Shared;

namespace Reklama.Models.Catalog
{
    public class ProductParamModel: BaseModel<ProductParam>, IProductParamRepository
    {
    }
}

Reklama/Models/Catalog/ProductParamValueModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Entity.Catalogs;
using Domain.Repository.Catalogs;
using Reklama.Models.Shared;

namespace Reklama.Models.Catalog
{
    public class ProductParamValueModel: BaseModel<ProductParamValue>, IProductParamValueRepository
    {
        public IQueryable<ProductParamValue> ReadByProduct(int productId)
        {
            return Read().Where(p => p.ProductId == productId);
        }
    }
}

Reklama/Models/Catalog/ProductSectionParamRefsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Entity.Catalogs;
using Domain.Repository.Catalogs;
using Reklama.Models.Shared;

namespace Reklama.Models.Catalog
{
    public class ProductSectionParamRefsModel : BaseModel<ProductSectionParamRef>, IProductSectionParamRefRepository
    {
        public override IQueryable<ProductSectionParamRef> Read()
        {
            return base.Read().OrderBy(r => r.CategoryId);
        }

        public IEnumerable<ProductSectionParamRef> ReadBySection(int sectionId)
        {
            return base.Read().Where(r => r.CategoryId == sectionId).OrderBy(r => r.Param.Name);
        }

        public IQueryable<ProductParam> ReadParamsBySection(int sectionId)
        {
            return (from r in ReadBySection(sectionId) select r.Param).AsQueryable();
        }
    }
}

Reklama/Models/Catalog/ProductSubsectionParamRefsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Entity.Catalogs;
using Domain.Repository.Catalogs;
using Reklama.Models.Shared;

namespace Reklama.Models.Catalog
{
    public class ProductSubsectionParamRefsModel : BaseModel<ProductSubsectionParamRef>, IProductSubsectionParamRefRepository
    {
        public override IQueryable<ProductSubsectionParamRef> Read()
        {
            return base.Read().OrderBy(r => r.SubsectionId);
        }

        public IEnumerable<ProductSubsectionParamRef> ReadBySubsection(int subsectionId)
        {
            return base.Read().Where(r => r.SubsectionId == subsectionId).OrderBy(r => r.Param.Name);
        }

        public IQueryable<ProductParam> ReadParamsBySubsection(int subsectionId)
        {
            return (from r in ReadBySubsection(subsectionId) select r.Param).AsQueryable();
        }
    }
}

Reklama/Models/Catalog/ShopCategoryRefModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Entity.Catalogs;
using Domain.Repository.Catalogs;
using Reklama.Models.Shared;

namespace Reklama.Models.Catalog
{
    public class ShopCategoryRefModel: BaseModel<ShopCategoryRef>, IShopCategoryRefRepository
    {

        public IQueryable<ShopCategoryRef> ReadByShop(int shopId)
        {
            return ((ReklamaContext)Context).ShopCategoryRefs.Where(x => x.ShopId == shopId);
        }

        public void Delete(int categoryId, int shopId)
        {
            var s = ((ReklamaContext)Context).ShopCategoryRefs.Where(x => x.ShopId == shopId && x.CategoryId == categoryId).FirstOrDefault();
            base.Delete(s);
        }
    }
}

Reklama/Models/Catalog/ShopCommentModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Entity.Catalogs;
using Reklama.Models.Shared;
using Domain.Repository.Catalogs;

namespace Reklama.Models.Catalog
{
    public class ShopCommentModel: BaseModel<ShopComment>, IShopCommentRepository 
    {
        public IQueryable<ShopComment> ReadByUser(int userId)
        {
            return Context.Set<ShopComment>().Where(sc => sc.UserId == userId);
        }

        public IQueryable<ShopComment> ReadByRealty(int shopId)
        {
            return Context.Set<ShopComment>().Where(sc => sc.ShopId == shopId);
        }
    }
}

Reklama/Controllers/BannersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Repository.Shared;
using Reklama.Data.Base;
using Reklama.Data.Entities;
using Reklama.Data.Servises;
using Reklama.Models;
using Reklama.Models.ViewModels.Banners;
using BannerTypes = Domain.Enums.BannerTypes;

namespace Reklama.Controllers
{
    public class BannersController : Controller
    {
        private string ParentController
        {
            get
            {
                return ControllerContext.ParentActionViewContext.RouteData.Values["Controller"] as string;
            }
        }

        private string ParentAction
        {
            get
            {
                return ControllerContext.ParentActionViewContext.RouteData.Values["Action"] as string;
            }
        }

        //
        // GET: /Under Filters Banner/

        private readonly BannerService _bannerService = new BannerService();

        public ActionResult GetUnderFiltersBanner()
        {
            var banner = _bannerService.GetBanner(ParentController, ParentAction, BannerTypes.UnderFilter);
            if(banner == null || banner.Images == null) return EmptyResult();

            return PartialView("Banners/_UnderFilters", new BannerViewModel
            {
                ImageUrl = banner.Images.ImagePath,
                Link = banner.Link,
                Target = "_blank"
            });
        }


        public ActionResult GetTopBanner()
        {
            var banner = _bannerService.GetBanner(ParentController, ParentAction, BannerTypes.Top);
            if (banner == null || banner.Images == null) return EmptyResult();

            return PartialView("Banners/_TopBanner", new BannerViewModel
            {
                ImageUrl = banner.Images.ImagePath,
                Link = banner.Link,
                Target = "_blank"
            });
        }

        public ActionResult GetMain1Banner()
        {
            var banner = _bannerService.GetBanner("Home", "Home", BannerTypes.Main1);
            if (banner == null || banner.Images == null) return EmptyResult();

            return PartialView("Banners/_Main1Banner", new BannerViewModel
            {
                ImageUrl = banner.Images.ImagePath,
                Link = banner.Link,
                Target = "_blank"
            });
        }

        public ActionResult GetMain2Banner()
        {
            var banner = _bannerService.GetBanner(ParentController, ParentAction, BannerTypes.Main2);
            if (banner == null || banner.Images == null)
            {
                var banner3 = _bannerService.GetBanner(ParentController, ParentAction, BannerTypes.Main3);
                if (banner3 == null || banner3.Images == null) return EmptyResult();
                return Empty23Result();
            }

            return PartialView("Banners/_Main23Banner", new BannerViewModel
            {
                ImageUrl = banner.Images.ImagePath,
                Link = banner.Link,
                Target = "_blank"
            });
        }

        public ActionResult GetMain3Banner()
        {
            var banner = _bannerService.GetBanner(ParentController, ParentAction, BannerTypes.Main3);
            if (banner == null || banner.Images == null)
            {
                var banner2 = _bannerService.GetBanner(ParentController, ParentAction, BannerTypes.Main2);
                if (banner2 == null || banner2.Images == null) return EmptyResult();
                return Empty23Result();
            }

            return PartialView("Banners/_Main23Banner", new BannerViewModel
            {
                ImageUrl = banner.Images.ImagePath,
                Link = banner.Link,
                Target = "_blank"
            });
        }

        private ActionResult EmptyResult()
        {
            return PartialView("Banners/_EmptyBanner");
        }


        private ActionResult Empty23Result()
        {
            return PartialView("Banners/_EmptyMain23Banner");
        }
    }
}

Reklama/Controllers/CurrencyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Repository.Shared;
using Reklama.Models;

namespace Reklama.Controllers
{
    public class CurrencyController : Controller
    {
        private ReklamaContext rc = new ReklamaContext();

        private ICurrencyRepository _currencyRepository;

        public CurrencyController(ICurrencyRepository currencyRepository)
        {
            _currencyRepository = currencyRepository;
            _currencyRepository.Context = rc;
        }

        //
        // GET: /Currency/List

        public ActionResult SwitcherList()
        {
            var currencies = _currencyRepository.Read();
            return View(currencies);
        }


        protected override void Dispose(bool disposing)
        {
            rc.Dispose();
            base.Dispose(disposing);
        }
    }
}

Reklama/Controllers/LinksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Entity.Admin;
using Domain.Repository.Admin;
using Domain.Repository.Other;
using Reklama.Models;


namespace Reklama.Controllers
{
    public class LinksController : Controller
    {
        private ReklamaContext rc = new ReklamaContext();

        private readonly IConfigRepository _configRepository;
        private readonly IPageRepository _pageRepository;

        public LinksController(IConfigRepository configRepository, IPageRepository pageRepository)
        {
            _configRepository = configRepository;
            _configRepository.Context = rc;

            _pageRepository = pageRepository;
            _pageRepository.Context = rc;
        }

        public ActionResult ViewSocialLinks()
        {
            ViewBag.Facebook = _configRepository.ReadByName("LinkFacebook").Value;
            ViewBag.Vk = _configRepository.ReadByName("LinkVk").Value;
            ViewBag.Twitter = _configRepository.ReadByName("LinkTwitter").Value;
            ViewBag.GooglePlus = _configRepository.ReadByName("LinkGooglePlus").Value;
            ViewBag.Odnoklassniki = _configRepository.ReadByName("LinkOdnoklassniki").Value;
            ViewBag.Mail = _configRepository.ReadByName("LinkMail").Value;
            return View();
        }


        /**
         * Отображает ссылку на одну из основных страниц, указанных в конфиге
         * (например, Пользовательское соглашение)
         */
        public ActionResult LinkToOneOfMainConfigPage(string mainPageName, string target = "_self", string cssClass = null)
        {
            try
            {
                var config = _configRepository.ReadByName(mainPageName);
                ViewBag.Page = _pageRepository.Read(Convert.ToInt32(config.Value));
                ViewBag.CssClass = cssClass;
                ViewBag.Target = target;
                return View(config);
            }
            catch
            {
                return null;
            }
        }


        protected override void Dispose(bool disposing)
        {
            rc.Dispose();
            base.Dispose(disposing);
        }
    }
}

Reklama/Views/Catalog/Details.cshtml
@using Domain.Enums
@using Reklama
@using Reklama.ViewModels.Catalog

@model DetailsViewModel
@{
    ViewBag.Title = string.Format("{0} - www.reklama.tm", Model.CurrentProduct.Title);
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="catalogInner">
    <table>
        <tr>
            <td class="ci1">
                @Html.Partial("_PlaceGoods")
                @Html.Partial("_Manufacturers", new ManufacturersMenuViewModel
                {
                    CurrentCategory = Model.CurrentProduct.Category,
                    Manufacturers = Model.Manufacturers
                    
                })
                @{ Html.RenderAction("GetUnderFiltersBanner", "Banners");}
   
            </td>
            <td class="ci2">
                <img width="10" height="1" border="0" src="/Images/System/s.png" />
            </td>
            <td class="ci3" valign="top">
                <div class="crumbs">
                    <a href="/">Главная страница</a>
                    <span class="arr">&rarr;</span>
                    @Html.ActionLink("Каталог товаров", "Index")
                    <span class="arr">&rarr;</span>
                    @Html.ActionLink(Model.CurrentProduct.Category.Name, "Category", new { secondCategoryId = Model.CurrentProduct.Category.ID })
                    <span class="arr">&rarr;</span>
                    @Model.CurrentProduct.Title
                </div>

                @Html.Partial("_Product", Model.CurrentProduct, (new ViewDataDictionary {
                        new KeyValuePair<string, object>("productMenu", ProductMenu.Characteristics)
                }))

                <div class="prodList">
                    <div class="prodListHead"><span>Технические характеристики</span></div>
                    <div class="prodListIn" id="scrollbarX">
                        <div class="viewport">
                            <div class="overview">
                                <ul>
                                    @foreach (var image in Model.CurrentProduct.ProductImage)
                                    {
                                        <li class="a">
                                            <div>
                                                <span>
                                                    <a id="sl_1" href="@Url.Action("Photos", new { id = Model.CurrentProduct.ID })">
                                                        <img src="/@string.Concat(ProjectConfiguration.Get.FilePaths["products"], image.ImageName)" />
                                                    </a>
                                                </span>
                                            </div>
                                        </li>
                                    }
                                </ul>
                            </div>
                        </div>
                        <div class="scrollbar">
                            <div class="track">
                                <div class="thumb">
                                    <div class="end"></div>
                                </div>
                            </div>
                        </div>




                    </div>
                </div>

                <div class="prodTable">
                    <table>
                        @*<tr>
                            <th>Общая информация</th>
                            <th></th>
                        </tr>*@

                        @foreach (var section2 in Model.Sections)
                        {
                            if (section2.Parameters.Any())
                            {
                                <tr>
                                    <th>@section2.Section.Name</th>
                                    <th></th>
                                </tr>

                                foreach (var parameter in section2.Parameters)
                                {
                                    <tr>
                                        <td>@parameter.Name</td>
                                        <td>
                                            @if (!String.IsNullOrEmpty(parameter.Value))
                                            {
                                                @parameter.Value@:&nbsp;@parameter.Unit
                                            }
                                            else
                                            {
                                                @:Не указано
                                    }
                                        </td>
                                    </tr>
                                }
                            }
                        }
                    </table>
                </div>

            </td>
        </tr>
    </table>
</div>
<div class="middleBot"></div>

Reklama/Views/Catalog/Feedbacks.cshtml
@using Domain.Entity.Catalogs
@using Domain.Enums
@using PagedList
@using Reklama.ViewModels.Catalog
@model ProductFeedbacksPageViewModel

@{
    ViewBag.Title = "Отзывы о товаре";
}

<div class="catalogInner">


    <table>
        <tr>
            <td class="ci1">
                @Html.Partial("_PlaceGoods")
                @Html.Partial("_Manufacturers", new ManufacturersMenuViewModel
                {
                    CurrentCategory = Model.Product.Category,
                    Manufacturers = Model.Product.Category.Product.Select(q => q.Manufacturer).Distinct()
                })
                @{ Html.RenderAction("GetUnderFiltersBanner", "Banners");}

            </td>
            <td class="ci2">
                <img width="10" height="1" border="0" src="/Images/System/s.png" />
            </td>
            <td class="ci3" valign="top">
                <div class="crumbs">
                    <a href="/">Главная страница</a>
                    <span class="arr">&rarr;</span>
                    @Html.ActionLink("Каталог товаров", "Index")
                    <span class="arr">&rarr;</span>
                    @Html.ActionLink(Model.Product.Category.Name, "Category", new { secondCategoryId = Model.Product.Category.ID })
                    <span class="arr">&rarr;</span>
                    @Model.Product.Title - Отзывы
                </div>
                
                @Html.Partial("_Product", Model.Product, (new ViewDataDictionary() { 
                        new KeyValuePair<string, object>("productMenu", ProductMenu.Feedback)
                }))
                
                
                @* List of comments *@
                @Html.Partial("_ProductComments", Model)
                

            </td>
        </tr>
    </table>
</div>
<div class="middleBot"></div>

Reklama/Views/Catalog/Index.cshtml
@using Reklama
@model IEnumerable<Reklama.Data.Entities.Group>
@{
    ViewBag.Title = "Каталог reklama.tm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="catalogMain">
    <div class="cmTop">
        @Html.Partial("_PlaceGoods")
        <p class="orangeText">@Html.Raw(ProjectConfiguration.Get.CatalogConfig.PromoText)</p>
    </div>
    @foreach (var category in Model.Where(q => q.Category.Any(w => w.IsActive) && q.Category.Any(w => w.Product.Any(e => e.IsActive)) ))
    {
        <p class="cmTitle">@category.Name</p>
        <ul>
            @foreach (var secondCategory in category.Category.Where(e => e.Product.Any(q => q.IsActive)))
            {
                var shopsProducts = secondCategory.Product.SelectMany(q => q.ShopProduct).ToList();
                <li>
                    @Html.ActionLink(secondCategory.Name, "Category", new { secondCategoryId = secondCategory.ID })
                    <sup>
                        <a href="javascript:void(0)">
                            @if (shopsProducts.Any())
                            {
                                @:от @Convert.ToInt32(shopsProducts.Min(p => p.Price)).ToString() $
                                                     }
                    </a>
                </sup>
                @if (secondCategory.IsNew)
                {
                    <a class="newImg" href="javascript:void(0)">
                        <img src="/Images/System/new.png" />
                    </a>
                }
            </li>
            }
        </ul>
    }
</div>
<div class="middleBot"></div>

Reklama/Views/Catalog/Photos.cshtml
@using Domain.Enums
@using Reklama
@using Reklama.Models.Shared
@using Reklama.ViewModels.Catalog
@model Reklama.Data.Entities.Product

@{
    ViewBag.Title = "Изображения товара";
}

<div class="catalogInner">


    <table>
        <tr>
            <td class="ci1">
                @Html.Partial("_PlaceGoods")
                @Html.Partial("_Manufacturers", new ManufacturersMenuViewModel
                {
                    CurrentCategory = Model.Category,
                    Manufacturers = Model.Category.Product.Select(q => q.Manufacturer).Distinct()
                })
                @{ Html.RenderAction("GetUnderFiltersBanner", "Banners");}
               
            </td>
            

            <td class="ci2">
                <img width="10" height="1" border="0" src="/Images/System/s.png" />
            </td>
            <td class="ci3" valign="top">
                <div class="crumbs">
                    <a href="/">Главная страница</a>
                    <span class="arr">&rarr;</span>
                    @Html.ActionLink("Каталог товаров", "Index")
                    <span class="arr">&rarr;</span>
                    @Html.ActionLink(Model.Category.Name, "Category", new { secondCategoryId = Model.Category.ID })
                    <span class="arr">&rarr;</span>
                    @Model.Title - Фотографии
                </div>
                
                @Html.Partial("_Product", Model,  (new ViewDataDictionary() { 
                        new KeyValuePair<string, object>("productMenu", ProductMenu.Photo),
                        new KeyValuePair<string, object>("isIssetInBookmarks", ViewBag.IsIssetInBookmark)
                }))
                
                @Html.Partial("SlideShow", new SliderModel
                     {
                         Slides = Model.ProductImage.Select(q => String.Format("/Images/Catalog/Product/{0}", q.ImageName)).ToList(),
                         Thumbnails = Model.ProductImage.Select(q => String.Format("/Images/Thumbnails/Product/{0}", q.ImageName)).ToList(),
                     })

            </td>
        </tr>
    </table>
</div>
<div class="middleBot"></div>


@section Scripts{
    @Scripts.Render("~/Scripts/cusel-min-2.5.js")
    @Scripts.Render("~/Scripts/jquery.tinyscrollbar.min.js")
    @Scripts.Render("~/Scripts/jquery.jcarousel.min.js")
    @Styles.Render("~/Content/Cusel.css")
    @Styles.Render("~/Content/Tinyscrollbar.css")
}

Reklama/Views/Catalog/_ProductCommentCreate.cshtml
@model Reklama.Models.ViewModels.Catalog.ProductCommentViewModel
@using CaptchaMvc.HtmlHelpers

@*<script src="~/Scripts/jquery-1.7.1.min.js"></script>*@
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<div class="itemResponseAdd">
    <em>Оставить отзыв</em>
    @using (Html.BeginForm("Create", "Catalog", FormMethod.Post))
    {
        @Html.ValidationSummary()

        <div class="respArea">
            @Html.TextAreaFor(c => c.Comment)
        </div>
        <div class="clear"></div>
        <div class="respRules">
            <p>рекомендуем ознакомиться -</p>
            <p>
                @{ Html.RenderAction("LinkToOneOfMainConfigPage", "Links", new { mainPageName = "UserAgreement" }); }
            </p>
        </div>
        @Html.EditorFor(c => c.CommentId)
        @Html.EditorFor(c => c.ProductId)
        @Html.AntiForgeryToken()
        <div class="respSubm">
            @if(User.Identity.IsAuthenticated)
            {
                <input type="submit" value="" />
            }
            else
            {
                <div class="itemNothingResponse">Для отправки комментариев необходимо @Html.ActionLink("авторизоваться", "Login", "Account", new { returnUrl = Url.Action("Feedbacks", "Catalog", new { id = Model.ProductId }) }, null)</div>
            }
        </div>

    }
</div>

Reklama/Views/Catalog/_ProductCurrencyPartial.cshtml
@model Reklama.Data.Entities.Product
@{
    Layout = null;
}

@if (Model.ShopProduct.Any())
{
    var maxPrice = Model.ShopProduct.Max(p => p.Price).Value;
    var minPrice = Model.ShopProduct.Min(p => p.Price).Value;
    <div class="prodPrice">
        <div class="mPrice alSelect">
            <img src="/Images/System/mPriceL.png" class="mPriceL">
            <img src="/Images/System/mPriceR2.png" class="mPriceR2">
            <label class="productMinPrice" value="@minPrice.ToString(System.Globalization.CultureInfo.InvariantCulture)">@Math.Round(minPrice, 2).ToString("0.#####", System.Globalization.CultureInfo.InvariantCulture)</label>
            @if (Math.Abs(maxPrice - minPrice) > (decimal)0.5)
            {
                @: - <label class="productMaxPrice" value="@maxPrice.ToString(System.Globalization.CultureInfo.InvariantCulture)">@Math.Round(maxPrice, 2).ToString("0.#####", System.Globalization.CultureInfo.InvariantCulture)</label>
                    }
            <span>USD</span>
            @{
            Html.RenderAction("SwitcherList", "Currency"); 
            }
        </div>
    </div>
}

@Scripts.Render("~/Scripts/ProductCurrencyDetails.js")